In [ ]:
from transformers import pipeline

# Load a text generation model
generator = pipeline("text-generation", model="gpt2")

# Generate text
result = generator(
    "Artificial Intelligence is",
    max_length=50,
    num_return_sequences=1
)

print(result[0]["generated_text"])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'num_return_sequences', 'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Artificial Intelligence is a good idea because it has the potential to drive the future, but it's also a little bit more complicated. We're not going to be able to build a machine that's more like a human being, but at least it can understand its surroundings, and it can think about what it does.

If you were to take a computer and turn it on and off, how would it do that?

You can look at a computer that is going to do that. It can do that. When you look at a car, you can turn on and off. You can turn on and off. That's the way it works. It doesn't know what to do. It can't think about what it is doing. And it can't do that. The way we're going to be able to do that is going to keep getting better.

You're saying that, for example, a computer that's doing the job is going to be able to decide which direction the car is going to go in, and then it can decide where to go next.

That's pretty interesting, as far as the idea of something that can just do one thing, say, a job, and then turn that on and off, and it can just decide

In [ ]:
classifier = pipeline('sentiment-analysis' , model = 'distilbert-base-uncased-finetuned-sst-2-english')

result = classifier('i love ai learning')

print(result)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.999502420425415}]

In [ ]:
from transformers import AutoTokenizer , AutoModel

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

model = AutoModel.from_pretrained('bert-base-cased')

text = ' i love AI'
token = tokenizer.tokenize(text)
print(token)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  436MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['i', 'love', 'AI']

In [ ]:
result = classifier('i hate eating pizza ')

print(result)

[{'label': 'NEGATIVE', 'score': 0.998256504535675}]

In [ ]:
generator = pipeline('text-generation', model = 'gpt2')

result = generator(
    'AI is powerfull and ',
    max_new_tokens = 50
)

print(result)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'AI is powerfull and \xa0can use any kind of power source, it can control almost any device that is connected to the Internet.\nIn the first episode, we learn that the world is a little bit different. We see that the world is full of people who can'}]

In [ ]:
model = AutoModel.from_pretrained('bert-base-cased')

text = 'i love learning AI'

input = tokenizer(text , return_tensors = 'pt')

output = model(**input)

print(output)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.5091,  0.0221, -0.2219,  ...,  0.0912,  0.5604,  0.2564],
         [ 0.4241, -0.5871,  0.6213,  ...,  0.0691,  0.2596,  0.4696],
         [ 0.4432, -0.2030, -0.2654,  ...,  0.5452, -0.2064,  0.0801],
         [ 0.1036,  0.0071,  0.0614,  ...,  0.0876,  0.2315,  0.0565],
         [ 0.5675,  0.1866, -0.1418,  ..., -0.1066,  0.5851,  0.1936],
         [ 1.0497,  0.1470, -0.2209,  ...,  0.6642,  1.4771, -0.0884]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-7.9762e-01,  5.4984e-01,  9.9995e-01, -9.9550e-01,  9.6931e-01,
          8.5924e-01,  9.9044e-01, -9.7745e-01, -9.8378e-01, -5.8601e-01,
          9.8873e-01,  9.9905e-01, -9.9445e-01, -9.9990e-01,  7.3017e-01,
         -9.8535e-01,  9.9287e-01, -6.3373e-01, -9.9998e-01, -7.6268e-01,
         -4.4698e-01, -9.9992e-01,  3.4142e-01,  9.5664e-01,  9.8493e-01,
          1.0100e-01,  9.9266e-01,  9.9998e-01,  8.9201e-01, -5.6585e-02,
          3.8490e-01, -9.9388e-01,  7.1813e-01, -9.9938e-01,  3.2230e-01,
          6.7327e-02,  5.7466e-01, -4.0019e-01,  7.0346e-01, -9.3743e-01,
         -7.0239e-01, -7.3761e-01,  6.5389e-01, -6.1185e-01,  8.3116e-01,
          5.0508e-01,  2.2846e-01, -8.7156e-03, -2.6761e-01,  9.9995e-01,
         -9.7406e-01,  9.9985e-01, -9.8940e-01,  9.9904e-01,  9.9667e-01,
          5.2378e-01,  9.9663e-01,  2.2734e-01, -9.9394e-01,  4.2013e-01,
          9.8081e-01,  3.3676e-02,  9.0391e-01, -1.6184e-01,  2.8780e-02,
         -5.8156e-01, -9.0192e-01,  3.2881e-01, -5.3594e-01,  4.0270e-01,
          4.2980e-01,  4.5568e-01,  9.9033e-01, -9.2818e-01, -6.2708e-02,
         -9.0788e-01,  2.5912e-01, -9.9994e-01,  9.4828e-01,  9.9998e-01,
          7.4902e-01, -9.9978e-01,  9.9664e-01, -4.3589e-01, -6.1323e-01,
          1.7895e-01, -9.9680e-01, -9.9960e-01,  8.8203e-02, -6.9235e-01,
          9.1849e-01, -9.9265e-01,  4.0981e-01, -8.6407e-01,  9.9999e-01,
         -9.1825e-01, -2.1607e-01,  4.5395e-01,  7.6102e-01, -6.2691e-01,
         -7.6915e-01,  7.8168e-01,  9.9658e-01, -9.8326e-01,  9.9557e-01,
          5.3965e-01, -9.5910e-01, -8.2269e-01,  5.4538e-01,  2.8968e-01,
          9.9242e-01, -9.9521e-01, -7.0311e-01,  1.3717e-01,  9.0610e-01,
         -9.3376e-01,  9.9442e-01,  8.8012e-01, -3.6133e-01,  9.9999e-01,
         -2.7804e-01,  9.1748e-01,  9.9887e-01,  6.7160e-01, -7.3179e-01,
         -2.8618e-01, -4.0545e-01,  8.0845e-01, -4.4869e-01, -4.3477e-01,
          7.7343e-01, -9.9278e-01, -9.9265e-01,  9.9962e-01, -3.7495e-01,
          9.9998e-01, -9.9942e-01,  9.7866e-01, -9.9997e-01, -7.7739e-01,
         -5.6328e-01, -1.4040e-02, -9.6175e-01,  1.8700e-01,  9.9502e-01,
          7.2983e-02, -7.6237e-01, -6.9713e-01,  4.0639e-01, -7.8038e-01,
          6.2805e-01,  7.1422e-01, -9.6083e-01,  9.9954e-01,  9.9054e-01,
          8.3750e-01,  9.3987e-01,  3.0803e-01, -8.7637e-01,  8.8541e-01,
          9.9182e-01, -9.9964e-01,  5.7396e-01, -9.7357e-01,  9.9948e-01,
          9.7759e-01,  6.3269e-01, -9.8920e-01,  9.9995e-01, -3.6058e-01,
          3.3628e-02, -7.4419e-02, -1.5348e-01, -9.9659e-01,  5.4542e-01,
          5.5412e-01,  8.2386e-01,  9.9979e-01, -9.9663e-01,  9.9985e-01,
          9.9092e-01, -2.7635e-02,  8.0975e-01,  9.9559e-01, -9.9739e-01,
         -9.8402e-01, -9.9219e-01,  3.6022e-01,  6.4514e-01,  6.4297e-01,
          4.1561e-01,  9.7287e-01,  9.9474e-01,  6.6023e-01, -9.9886e-01,
         -3.9371e-01,  9.8430e-01, -3.0390e-01,  9.9998e-01,  6.1703e-02,
         -9.9987e-01, -7.6824e-01,  8.9604e-01,  9.9304e-01, -3.2670e-01,
          9.8816e-01, -5.8630e-01, -1.1683e-01,  9.6714e-01, -9.9957e-01,
          9.9380e-01, -1.5958e-02,  6.5812e-01,  9.1239e-01,  9.9386e-01,
         -7.7458e-01, -2.1094e-01,  3.4339e-01, -6.2524e-01,  9.9994e-01,
         -9.9970e-01, -3.3686e-01,  4.7919e-01, -9.9676e-01, -9.9852e-01,
          9.8187e-01, -8.4465e-02, -5.1549e-01, -2.4729e-01,  1.4566e-01,
          2.8564e-01,  8.7843e-01,  9.9033e-01, -4.9389e-01, -3.6747e-01,
         -9.9991e-01, -9.8632e-01, -8.8491e-01, -9.4387e-01,  1.3082e-01,
          7.3068e-01, -3.9854e-01, -9.5463e-01, -9.9487e-01,  9.7172e-01,
          8.3035e-01, -8.5882e-01, -3.2115e-01, -5.0636e-01, -9.9437e-01,
          5.7246e-01, -8.1388e-01, -9.9920e-01,  9.9973e-01, -6.1904e-01,
          9.8457e-01,  9.7774e-01, -9.9525e-01,  6.3239e-01, -9.9556e-01,
         -5.0607e-02, -9.9966e-01,  3.7032e-01,  3.1635e-01, -6.4460e-01,
         -1.3404e-01,  9.9551e-01, -9.7710e-01, -3.7037e-01,  8.1819e-01,
         -9.9994e-01,  9.4831e-01, -2.7643e-01,  9.9932e-01,  7.3081e-01,
         -9.3102e-02,  9.9094e-01,  8.9107e-01, -9.9149e-01, -9.9989e-01,
          9.2261e-01,  9.9671e-01, -9.9539e-01, -2.4773e-01,  9.9996e-01,
         -9.9265e-01, -8.4112e-01, -9.4874e-01, -9.9687e-01, -9.9983e-01,
          1.4131e-01, -7.9298e-01,  6.6362e-02,  9.9125e-01,  3.9331e-01,
          1.0049e-01,  9.9574e-01,  9.9820e-01,  1.0441e-01, -1.4952e-01,
          3.2246e-02, -9.8764e-01, -9.9844e-01,  7.5249e-01,  2.2370e-01,
         -9.9998e-01,  9.9993e-01, -9.9534e-01,  9.9970e-01,  6.6588e-01,
         -9.8018e-01,  8.8529e-01,  6.3331e-02, -9.1759e-01,  2.0584e-02,
          9.9995e-01,  9.9066e-01, -1.7359e-01,  2.0399e-01,  8.5441e-01,
         -1.1162e-01,  4.7687e-01, -6.7667e-01, -5.3254e-01,  2.9605e-01,
         -9.5753e-01,  9.8113e-01,  6.8509e-01, -9.9515e-01,  9.8745e-01,
          1.5441e-01,  7.8672e-01, -7.2430e-01,  9.1547e-01,  9.9381e-01,
         -2.0748e-01, -3.8789e-01, -1.8514e-01, -9.2966e-01, -9.5737e-01,
          1.9148e-01, -9.9515e-01, -3.1121e-01,  8.9175e-01,  9.8717e-01,
         -9.9332e-01,  9.9864e-01, -1.6444e-01,  8.9173e-01, -9.9334e-01,
          9.9999e-01, -9.9909e-01,  1.8161e-01,  6.7610e-01, -7.4329e-01,
         -2.5008e-01,  9.9368e-01,  9.7163e-01,  9.5085e-01, -8.5131e-01,
         -6.6231e-01,  8.7660e-01,  9.8246e-01, -9.5956e-01,  1.0651e-02,
         -9.9741e-01, -5.5532e-01,  9.9781e-01,  9.8558e-01, -1.3931e-01,
         -5.1273e-01, -9.9268e-01,  9.7454e-01, -6.6206e-01, -9.1883e-01,
         -2.0815e-01, -7.2617e-01,  5.4965e-01,  9.9356e-01, -4.8169e-01,
          7.2720e-01,  2.2398e-01, -9.9384e-01,  8.8777e-01,  7.8062e-01,
          9.9989e-01, -9.7818e-01,  4.3809e-01,  9.9036e-01, -2.8555e-01,
         -6.8357e-01,  6.2851e-01,  9.9457e-01, -9.7703e-01, -3.8001e-01,
         -9.9969e-01,  1.5108e-02, -7.4959e-01, -2.2696e-01, -5.8620e-01,
          1.7587e-01, -8.1437e-01,  9.3041e-01,  3.3489e-02,  8.3565e-01,
         -2.9769e-01,  9.8181e-01, -3.2964e-01, -9.9519e-02, -3.8178e-01,
          5.9219e-02,  5.5255e-01,  1.2485e-01,  9.8891e-01, -9.7509e-01,
          9.9990e-01, -4.1685e-01, -9.9997e-01, -9.9224e-01, -6.6673e-01,
         -9.9981e-01,  4.9856e-01, -9.9851e-01,  9.9193e-01,  8.6856e-01,
         -9.9484e-01, -9.9647e-01, -9.9929e-01, -9.9959e-01,  8.7116e-01,
          5.5456e-01, -1.6102e-01,  2.6629e-02,  9.0258e-01,  8.1293e-02,
         -9.6910e-02, -1.2295e-01, -9.5984e-01, -3.8882e-01, -9.9448e-01,
          6.7998e-01, -9.9998e-01, -5.6572e-01,  9.9524e-01, -9.9024e-01,
         -8.8157e-01, -9.4651e-01, -5.9735e-01, -8.8604e-01,  5.2924e-01,
          9.8988e-01, -2.9727e-01, -6.9756e-01, -9.9980e-01,  9.9382e-01,
         -7.0240e-01,  1.8360e-01, -6.6900e-01, -9.8622e-01,  9.9983e-01,
          6.4212e-01, -6.8101e-02, -2.5459e-01, -9.9933e-01,  9.6848e-01,
         -9.0175e-01, -8.9387e-01, -9.8882e-01,  1.8569e-01, -9.7283e-01,
         -9.9992e-01,  1.4302e-01,  9.8622e-01,  9.9875e-01,  9.8697e-01,
          3.4160e-01, -4.7445e-01, -9.7761e-01,  2.7217e-01, -9.9998e-01,
          5.4712e-01,  8.0876e-01, -9.8832e-01, -7.2329e-01,  9.9574e-01,
          9.8345e-01, -8.9019e-01, -9.6294e-01,  6.7389e-01,  5.8601e-01,
          9.7462e-01, -3.3179e-01, -5.3731e-01,  3.9499e-01, -1.1528e-01,
         -9.9444e-01, -9.4545e-01,  9.9679e-01, -9.9685e-01,  9.8796e-01,
          9.8588e-01,  9.9624e-01, -1.5628e-01,  9.7348e-02, -9.7497e-01,
         -9.9905e-01, -6.6570e-01,  2.2150e-01, -9.9996e-01,  9.9996e-01,
         -9.9998e-01,  4.5244e-01, -3.9869e-01,  7.7444e-01,  9.9393e-01,
         -2.6638e-01, -9.9995e-01, -9.9991e-01,  1.6547e-01,  1.3978e-02,
          9.9476e-01,  1.4440e-01,  3.3979e-01, -6.2125e-01, -3.6032e-02,
          9.9822e-01, -6.1483e-01, -2.2944e-01, -9.9329e-01,  9.9979e-01,
          6.5844e-01, -9.9858e-01,  9.8875e-01, -9.9969e-01,  7.2393e-01,
          9.8658e-01,  9.0894e-01,  9.8133e-01, -9.9641e-01,  9.9999e-01,
         -9.9991e-01,  9.9940e-01, -9.9999e-01, -9.9648e-01,  9.9988e-01,
         -9.9451e-01, -7.8222e-01, -9.9983e-01, -9.9327e-01,  6.7300e-01,
          2.3976e-01, -6.3707e-01,  9.9174e-01, -9.9990e-01, -9.9869e-01,
          1.5880e-01, -8.4475e-01, -6.3872e-01,  9.8725e-01, -5.3031e-01,
          9.9327e-01, -6.8782e-02,  9.7149e-01,  1.5773e-01,  9.9319e-01,
          9.9966e-01, -7.0235e-01, -5.6154e-01, -9.9467e-01,  9.9259e-01,
         -6.7086e-01,  4.9407e-01,  9.7417e-01, -3.7824e-02, -5.8481e-01,
          5.2692e-01, -9.9790e-01,  5.5397e-01, -7.0040e-01,  8.2229e-01,
          9.0694e-01,  8.7461e-01,  1.4572e-01, -4.7169e-01, -1.6339e-01,
         -9.9543e-01,  6.6174e-01, -9.9976e-01,  9.8840e-01, -9.0837e-01,
          1.4340e-01, -4.4316e-01,  3.5854e-01, -9.7272e-01,  9.9974e-01,
          9.9893e-01, -9.9987e-01,  2.6574e-01,  9.9096e-01, -7.1690e-01,
          9.8009e-01, -9.9551e-01, -6.3483e-02,  9.3659e-01, -8.0687e-01,
          9.8975e-01,  1.9623e-01, -1.7680e-01,  9.8840e-01, -9.9692e-01,
         -8.4557e-01, -7.8827e-01,  2.3313e-01,  1.2025e-01, -9.7964e-01,
          1.7839e-01,  9.5338e-01, -3.9961e-01, -9.9983e-01,  8.1117e-01,
         -9.9959e-01, -2.9506e-01,  9.8791e-01, -2.4563e-04,  9.9995e-01,
         -7.2494e-01,  4.4144e-02,  8.6474e-03, -9.9982e-01, -9.9665e-01,
          2.1801e-01, -1.9601e-01, -9.4206e-01,  9.9762e-01, -1.2129e-01,
          8.0839e-01, -9.9995e-01,  4.4369e-01,  9.8765e-01,  4.0048e-01,
          8.5149e-01, -6.9348e-01, -9.6920e-01, -9.4743e-01, -8.3244e-01,
          1.1025e-01,  8.4558e-01, -9.8847e-01, -6.5547e-01, -8.1731e-01,
          9.9998e-01, -9.9807e-01, -9.2810e-01, -9.9056e-01,  5.8808e-01,
          8.0953e-01,  4.8059e-01,  8.7603e-02, -8.7503e-01,  8.6635e-01,
         -8.6314e-01,  9.9783e-01, -9.9641e-01, -9.9754e-01,  9.9986e-01,
          1.3947e-01, -9.8389e-01, -1.2237e-01, -4.4190e-01,  1.4169e-01,
         -1.6797e-02,  6.0605e-01, -9.1655e-01, -3.0408e-01, -9.9940e-01,
          6.8004e-01, -7.9977e-01, -9.9496e-01, -6.6583e-01, -3.7220e-01,
         -9.9975e-01,  9.9564e-01,  9.7893e-01,  9.9997e-01, -9.9987e-01,
          8.8591e-01,  2.0395e-01,  9.9938e-01,  4.3145e-02, -7.3290e-01,
          8.0866e-01,  9.9983e-01, -5.7355e-01,  8.5502e-01, -2.5954e-02,
         -2.1053e-02,  3.8922e-01, -5.7474e-01,  9.8744e-01, -8.7897e-01,
          3.8282e-01, -9.8283e-01, -9.9995e-01,  9.9996e-01, -1.2424e-01,
          9.9561e-01,  4.1342e-01,  6.8434e-01, -8.6461e-01,  9.5872e-01,
         -9.5445e-01, -9.4158e-01, -9.9999e-01,  3.2523e-01, -9.9984e-01,
         -9.9299e-01,  5.3097e-02,  9.9219e-01, -9.9976e-01, -9.9472e-01,
         -2.9569e-01, -9.9999e-01,  9.0025e-01, -9.7809e-01, -6.9882e-01,
         -9.9037e-01,  9.9408e-01, -4.0039e-01, -5.1489e-01,  9.6845e-01,
         -9.7779e-01,  8.9739e-01,  9.1537e-01,  6.1406e-01,  3.5472e-01,
          2.1056e-01, -7.8546e-01, -9.8404e-01, -7.0650e-01, -9.8016e-01,
          7.2932e-01, -9.9127e-01, -8.5561e-01,  9.9735e-01,  9.8948e-01,
         -9.9944e-01, -9.9701e-01,  9.8503e-01,  4.7256e-03,  9.9131e-01,
         -5.3428e-01, -9.9991e-01, -9.9993e-01,  1.7952e-01, -1.5894e-01,
          9.9577e-01, -4.4474e-01,  9.9936e-01,  8.5376e-01, -1.0228e-01,
          5.9922e-01, -4.6301e-01, -2.6416e-01, -4.0969e-01, -3.3119e-01,
          9.9998e-01, -8.3318e-01,  9.8980e-01]], grad_fn=<TanhBackward0>), hidden_states=None, past_key_values=None, attentions=None, cross_attentions=None)

In [ ]:
from transformers import pipeline
# Load a pre-trained Q&A pipeline
qa_pipeline = pipeline("question-answering", model="deepset/roberta-base-squad2")

# Define the context and question
context = "Hugging Face is a company that provides open-source tools for NLP."
question = "What does Hugging Face provide?"

# Get the answer
result = qa_pipeline(question=question, context=context)
print(f"Answer: {result['answer']}")

KeyError: "Unknown task question-answering, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [ ]:
# Upgrade the transformers library to ensure 'question-answering' task is recognized.
!pip install --upgrade transformers

After running the cell above to upgrade `transformers`, **please restart the runtime (Runtime > Restart runtime) to apply the changes**. Then, you can run the following cell to use the `question-answering` pipeline. I've included a common model for question answering.

In [ ]:
from transformers import pipeline

# Initialize the question-answering pipeline with a specific model
qa = pipeline("question-answering", model="distilbert-base-cased-distilled-squad")

result = qa(
    question = "what is AI?",
    context =
        """artificial intelligence is the simulation of human intelligence in machine """
)


print(result)

In [ ]:
from transformers import pipeline
translator = pipeline('Naereen/english-to-french-translation-for-Magic-the-Gathering')

result = translator('I love AI')
print(result)

In [ ]:


from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,

)

import torch

In [ ]:
text = ' i love AI'

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

model = AutoModelForSequenceClassification.from_pretrained('bert-base-cased')
inputs = tokenizer(
    text,
    return_tensors = 'pt'
)

print(inputs)

ouputs = model(**inputs)

outputs = model(
    inputs_ids = inputs['input_ids'],
    attention_mask = inputs['attention_mask']
)

print(outputs.logits)

predicted_class = torch.argmax(
    ouputs.logits,
    dim = 1
)

print(predicted_class)

label = model.config.id2label[predicted_class.item]

NameError: name 'AutoModelForSequenceClassification' is not defined

In [ ]:
from transformers import pipeline

generator = pipeline(
    'text2text-generation',
    model = 'google/flan-t5-base'
)

print(generator)

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

KeyError: "Unknown task text2text-generation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [ ]:
text = ''' Artificial intelligence is being used in healthcare , finance , education , and transportation'''

prompt = 'summarizer: '+text

result = generator(prompt , max_new_tokens = 50)

print(result[0]['generated_text'])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

summarizer:  Artificial intelligence is being used in healthcare , finance , education , and transportation , 10.1016/j.ac.2010.09.003 , 67 , 1 , (28-35) , .

Chang Wang, Yanlin Wang, Lingwei Wang, Wenjun Li, Yongkun Li and Xiaoying

In [ ]:
! pip install -q transformers datasets pandas

In [ ]:
from datasets import load_dataset
from transformers import AutoTokenizer

import pandas as pd
import random





print("="*80)
print("Downloading datasets")
print("="*80)
dataset=load_dataset("stanfordnlp/imdb",trust_remote_code=True)
print()
print('dataset downloaded successfully ')

print('='*80)
print('dataset summary')
print('='*80)

print(dataset)


print()
print('='*80)
print('available split ')
print('='*80)



# step 6

print('='*80)
print('number of samples ')
print('='*80)

print('tranning samples :', len(dataset['train']))
print('testing samples',len(dataset['test']))

print('unsupervised samples :', len(dataset['unsupervised']))



# step 7

print()
print(' frist training sample ')
print('='*80)

print(dataset['train'][0])

# frist 3 reviews

print()
print('='*80)
print(' frist 3 reveiws')

for i in range(3):
  print('review_number :',i+1)
  print('*'*60)
  print(dataset['train'][i]['text'])
  print('label', dataset['train'][i]['label'])
  print('*'*60)
  print()

`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'stanfordnlp/imdb' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.
ERROR:datasets.load:`trust_remote_code` is not supported anymore.
Please check that the Hugging Face dataset 'stanfordnlp/imdb' isn't based on a loading script and remove `trust_remote_code`.
If the dataset is based on a loading script, please ask the dataset author to remove it and convert it to a standard format like Parquet.

================================================================================
Downloading datasets
================================================================================

dataset downloaded successfully
================================================================================
dataset summary
================================================================================
DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

================================================================================
available split
================================================================================
================================================================================
number of samples
================================================================================
tranning samples : 25000
testing samples 25000
unsupervised samples : 50000

 frist training sample
================================================================================
{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

================================================================================
 frist 3 reveiws
review_number : 1
************************************************************
I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it's not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn't have much of a plot.
label 0
************************************************************

review_number : 2
************************************************************
"I Am Curious: Yellow" is a risible and pretentious steaming pile. It doesn't matter what one's political views are because this film can hardly be taken seriously on any level. As for the claim that frontal male nudity is an automatic NC-17, that isn't true. I've seen R-rated films with male nudity. Granted, they only offer some fleeting views, but where are the R-rated films with gaping vulvas and flapping labia? Nowhere, because they don't exist. The same goes for those crappy cable shows: schlongs swinging in the breeze but not a clitoris in sight. And those pretentious indie movies like The Brown Bunny, in which we're treated to the site of Vincent Gallo's throbbing johnson, but not a trace of pink visible on Chloe Sevigny. Before crying (or implying) "double-standard" in matters of nudity, the mentally obtuse should take into account one unavoidably obvious anatomical difference between men and women: there are no genitals on display when actresses appears nude, and the same cannot be said for a man. In fact, you generally won't see female genitals in an American film in anything short of porn or explicit erotica. This alleged double-standard is less a double standard than an admittedly depressing ability to come to terms culturally with the insides of women's bodies.
label 0
************************************************************

review_number : 3
************************************************************
If only to avoid making this type of film in the future. This film is interesting as an experiment but tells no cogent story.<br /><br />One might feel virtuous for sitting thru it because it touches on so many IMPORTANT issues but it does so without any discernable motive. The viewer comes away with no new perspectives (unless one comes up with one while one's mind wanders, as it will invariably do during this pointless film).<br /><br />One might better spend one's time staring out a window at a tree growing.<br /><br />
label 0
************************************************************

In [ ]:
print('dataset feautures ')

print(dataset['train'].features)

label_names = dataset['train'].features['label'].names

print('label mapping ')
print(label_names)

dataset feautures
{'text': Value('string'), 'label': ClassLabel(names=['neg', 'pos'])}
label mapping
['neg', 'pos']

In [ ]:
# 10  display label as text

for i in range(3):
  sentiment = label_names[dataset['train'][i]['label']]

  print('sentiment', sentiment)

sentiment neg
sentiment neg
sentiment neg

In [ ]:
#11 random review

print('\n')
print('='*80)
print('random review')
print('='*80)

index = random.randint(0,len(dataset['train'])-1)

print(dataset['train'][index]['text'])

print('sentiment', label_names[dataset['train'][index]['label']])

================================================================================
random review
================================================================================
I had high expectations of this movie (the title, translated, is "How We Get Rid of the Others"). After all, the concept is great: a near future in which the ruling elite has taken the consequence of the right-wing government's constant verbal and legislative persecution of so-called freeloaders and the left wing in general, and decided to just kill off everyone who cannot prove that they're contributing something to the establishment (the establishment being called "the common good", but actually meaning the interests of the ruling capitalist ideology).<br /><br />Very cool idea! Ideal for biting satire! Only, this movie completely blows its chance. The satire comes out only in a few scenes and performances of absurdity, but this satire is not sustained; it is neither sharp nor witty. And for an alleged comedy, the movie has nearly no funny scenes. The comedy, I assume, is supposed to be in the absurdity of the situations, but the situations are largely uncomfortable and over-serious, rather than evoking either laughter or thought.<br /><br />The script is rife with grave errors in disposition. The action should have focused on the political aspects and how wrong it would be to do such a thing, but instead oodles of time are spent on a young woman who was the one that wrote the new laws for fun, and who's trying to save everybody, by organizing a resistance that ships people to Africa. All this is beside the point! A movie like this should not pretend to be so serious! It's a satire! A political statement. But it doesn't even begin to actually address the problem it's supposed to be about. Maybe it was afraid of going too far? How cowardly. That's not art. It's not even real satire.<br /><br />Søren Pilmark, a very serious and by now one of Denmark's absolutely senior actors, was very good. He largely carried what little entertainment value the movie had. Everybody else: nothing special (well, perhaps except for Lene Poulsen, who did supply a convincing performance).<br /><br />In fact, a problem with most Danish movies is that the language never sounds natural. Neither the formulation nor the delivery. Why is it so difficult to make it sound right? Why must it be so stilted and artificial? I hope, when people look at these movies fifty years from now, they don't think that this was how people talked in general Danish society.<br /><br />3 out of 10.
sentiment neg

In [ ]:
# 12 convert to pandas

df = dataset['train'].to_pandas()

print(df.head())
print('*'*60)
print(df.info())
print('*'*60)
print(df.describe())

                                                text  label
0  I rented I AM CURIOUS-YELLOW from my video sto...      0
1  "I Am Curious: Yellow" is a risible and preten...      0
2  If only to avoid making this type of film in t...      0
3  This film was probably inspired by Godard's Ma...      0
4  Oh, brother...after hearing about this ridicul...      0
************************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    25000 non-null  object
 1   label   25000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 390.8+ KB
None
************************************************************
             label
count  25000.00000
mean       0.50000
std        0.50001
min        0.00000
25%        0.00000
50%        0.50000
75%        1.00000
max        1.00000

In [ ]:
# 14
df.columns

Index(['text', 'label'], dtype='object')

In [ ]:
# 15
df.isnull().sum()

text     0
label    0
dtype: int64

In [ ]:
# 16
print(df['label'].value_counts())

label
0    12500
1    12500
Name: count, dtype: int64

In [ ]:
# 17

df['sentiment'] = df['label'].map({
    0:'negative',
    1:'positive'
})

print(df.head())

                                                text  label sentiment
0  I rented I AM CURIOUS-YELLOW from my video sto...      0  negative
1  "I Am Curious: Yellow" is a risible and preten...      0  negative
2  If only to avoid making this type of film in t...      0  negative
3  This film was probably inspired by Godard's Ma...      0  negative
4  Oh, brother...after hearing about this ridicul...      0  negative

In [ ]:
# 18 review length

df['review_length'] = df['text'].apply(len)

df.head()

,text,label,sentiment,review_length
0,I rented I AM CURIOUS-YELLOW from my video sto...,0,negative,1640
1,"""I Am Curious: Yellow"" is a risible and preten...",0,negative,1294
2,If only to avoid making this type of film in t...,0,negative,528
3,This film was probably inspired by Godard's Ma...,0,negative,706
4,"Oh, brother...after hearing about this ridicul...",0,negative,1814

In [ ]:
# 19 averge review length

df['review_length'].mean()

np.float64(1325.06964)

In [ ]:
#20 longest review
df['review_length'].max()

13704

In [ ]:
21 # smallest review
shortest = df['review_length'].min()
print(shortest)

print(df.loc[shortest,'text'])

print(df.loc[shortest,'review_length'])

52
Ned Kelly (Ledger), the infamous Australian outlaw and legend. Sort of like Robin Hood, with a mix of Billy the Kid, Australians love the legend of how he stood up against the English aristocratic oppression, and united the lower classes to change Australia forever. The fact that the lower classes of the time were around 70% immigrant criminals seems to be casually skimmed around by this film. Indeed, quite a few so called `facts' in this film are, on reflection, a tad dubious.<br /><br />I suppose the suspicions should have been aroused when, in the opening credits, it was claimed that this film is based upon the book, `Our Sunshine'. If ever a romanticized version of truth could be seen in a name for a book, there it was. This wasn't going to be a historical epic, but just an adaptation of one of many dubious legends of Ned Kelly, albeit a harsh and sporadically brutal version.<br /><br />Unfortunately, Ned Kelly is nothing more than an overblown Hallmark channel `real life historical drama' wannabe! The story plods along at an alarming rate (alarming because never has a film plodded so slowly!) The feeling of numbness after the two hours of pure drivel brought back memories of Costner's awful Wyatt Earp all those years ago. Simply put, nothing happens in the film, but it takes a long time getting to that nothing. This would possibly have been a tad more bearable if the performances were good (because the direction sure as heck wasn't). However, unless you are looking to play a game of spot the worst Oirish accent, then you're gonna be disappointed. Between that, the game of `Who has the stupidest beard?', `Spot the obvious backstabber!' (clue, they are all ginger for some reason), and `Nature in Australia.including lions', it is an experience similar to flicking through Hallmark, The History Channel, Discovery Channel, and Neighbours whilst suffering a huge hangover. Yup, nature pops up a lot, as to fill even more time (possibly an attempt to look arty), the film keeps showing pointless wildlife shots, and once all the native species are shown, here's a circus to allow for a camel and a lion (which is used during one fight to try to make us actually feel more sorry for the lion than the massacred people).<br /><br />This is a turgid, emotionless piece of historical fluff which should have gone straight to TV. There isn't even one good word I can say about this film. Even the usually fantastic Rush seems embarrassed to be here. When one of the characters comments that there is only 2 bullets left for him and his pal, I myself was wishing I had a gun to blow any memory of this film out of my head!
2645

In [ ]:
# tokenizer
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    'bert-base-uncased'
)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
# 23  tokenizer first review

review = dataset['train'][0]['text']

tokens = tokenizer(review)

print(tokens)

{'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 2107, 2004, 1996, 5148, 2162, 1998, 2679, 3314, 1999, 1996, 2142, 2163, 1012, 1999, 2090, 4851, 8801, 1998, 6623, 7939, 4697, 3619, 1997, 8947, 2055, 2037, 10740, 2006, 4331, 1010, 2016, 2038, 3348, 2007, 2014, 3689, 3836, 1010, 19846, 1010, 1998, 2496, 2273, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 2054, 8563, 2033, 2055, 1045, 2572, 8025, 1011, 3756, 2003, 2008, 2871, 2086, 3283, 1010, 2023, 2001, 2641, 26932, 1012, 2428, 1010, 1996, 3348, 1998, 16371, 25469, 5019, 2024, 2261, 1998, 2521, 2090, 1010, 2130, 2059, 2009, 1005, 1055, 2025, 2915, 2066, 2070, 10036, 2135, 2081, 22555, 2080, 1012, 2096, 2026, 2406, 3549, 2568, 2424, 2009, 16880, 1010, 1999, 4507, 3348, 1998, 16371, 25469, 2024, 1037, 2350, 18785, 1999, 4467, 5988, 1012, 2130, 13749, 7849, 24544, 1010, 15835, 2037, 3437, 2000, 2204, 2214, 2879, 2198, 4811, 1010, 2018, 3348, 5019, 1999, 2010, 3152, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1045, 2079, 4012, 3549, 2094, 1996, 16587, 2005, 1996, 2755, 2008, 2151, 3348, 3491, 1999, 1996, 2143, 2003, 3491, 2005, 6018, 5682, 2738, 2084, 2074, 2000, 5213, 2111, 1998, 2191, 2769, 2000, 2022, 3491, 1999, 26932, 12370, 1999, 2637, 1012, 1045, 2572, 8025, 1011, 3756, 2003, 1037, 2204, 2143, 2005, 3087, 5782, 2000, 2817, 1996, 6240, 1998, 14629, 1006, 2053, 26136, 3832, 1007, 1997, 4467, 5988, 1012, 2021, 2428, 1010, 2023, 2143, 2987, 1005, 1056, 2031, 2172, 1997, 1037, 5436, 1012, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
# inputs IDs - top 50

print(tokens['input_ids'][:50])

[101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023]

In [ ]:
# 25 : token names  - decoding the token ids

tokenizer.convert_ids_to_tokens(
    tokens['input_ids'][:50]
)

['[CLS]',
 'i',
 'rented',
 'i',
 'am',
 'curious',
 '-',
 'yellow',
 'from',
 'my',
 'video',
 'store',
 'because',
 'of',
 'all',
 'the',
 'controversy',
 'that',
 'surrounded',
 'it',
 'when',
 'it',
 'was',
 'first',
 'released',
 'in',
 '1967',
 '.',
 'i',
 'also',
 'heard',
 'that',
 'at',
 'first',
 'it',
 'was',
 'seized',
 'by',
 'u',
 '.',
 's',
 '.',
 'customs',
 'if',
 'it',
 'ever',
 'tried',
 'to',
 'enter',
 'this']

In [ ]:
# 26 - tokenize entire dataset

def tokenize(example):

  return tokenizer( example['text'],
                   truncation = True,
                    padding ='max_length',
                    max_length = 128
                    )

tokenized_dataset = dataset.map(
    tokenize , batched = True
)

print(tokenized_dataset)

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 50000
    })
})

In [ ]:
# 28
print(tokenized_dataset['train'][0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0, 'input_ids': [101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
# 29 display nuput ids
print(tokenized_dataset['train'][0]['input_ids'])

[101, 1045, 12524, 1045, 2572, 8025, 1011, 3756, 2013, 2026, 2678, 3573, 2138, 1997, 2035, 1996, 6704, 2008, 5129, 2009, 2043, 2009, 2001, 2034, 2207, 1999, 3476, 1012, 1045, 2036, 2657, 2008, 2012, 2034, 2009, 2001, 8243, 2011, 1057, 1012, 1055, 1012, 8205, 2065, 2009, 2412, 2699, 2000, 4607, 2023, 2406, 1010, 3568, 2108, 1037, 5470, 1997, 3152, 2641, 1000, 6801, 1000, 1045, 2428, 2018, 2000, 2156, 2023, 2005, 2870, 1012, 1026, 7987, 1013, 1028, 1026, 7987, 1013, 1028, 1996, 5436, 2003, 8857, 2105, 1037, 2402, 4467, 3689, 3076, 2315, 14229, 2040, 4122, 2000, 4553, 2673, 2016, 2064, 2055, 2166, 1012, 1999, 3327, 2016, 4122, 2000, 3579, 2014, 3086, 2015, 2000, 2437, 2070, 4066, 1997, 4516, 2006, 2054, 1996, 2779, 25430, 14728, 2245, 2055, 3056, 2576, 3314, 102]

In [ ]:
# 30 display the attention mask - padded gets 0 - real token get 1 , all are one's beacuse batch sizes are small enoguh(128)

print(tokenized_dataset['train'][0]['attention_mask'])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
# named ENtity Recognition
from transformers import pipeline

ner = pipeline('ner')

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.33GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

In [ ]:
text  =' Elon Musk is mad person'

entities = ner(text)
print(entities)

[{'entity_group': 'PER', 'score': np.float32(0.99579704), 'word': 'Elon Musk', 'start': 1, 'end': 10}]

In [ ]:
ner = pipeline('ner', aggregation_strategy='simple')

entities = ner(text)
print(entities)

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[{'entity_group': 'PER', 'score': np.float32(0.99579704), 'word': 'Elon Musk', 'start': 1, 'end': 10}]

In [ ]:
for entity in entities:
  print('entity:', entity['word'], 'TYpe:',entity['entity_group'])

In [ ]:
entity_names = []

for entity in entities:
  entity_names.append(entity['word'])

print(entity_names)

['Elon Musk']

In [ ]:
people = []

for entity in entities :
  if entity['entity_group'] == 'PER':
    people.append(entity['word'])

print(people)

['Elon Musk']

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification
)

tokenizer = AutoTokenizer.from_pretrained('dslim/bert-base-NER')

model = AutoModelForTokenClassification.from_pretrained('dslim/bert-base-NER')

model.safetensors: reconstructing file:   0%|          |  0.00B /  433MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
inputs = tokenizer(text , return_tensors='pt')
outputs = model(**inputs)

print(outputs)

TokenClassifierOutput(loss=None, logits=tensor([[[ 0.6089,  0.4165],
         [-0.1005,  0.1340],
         [-0.0843,  0.2771],
         [ 0.1716, -0.0807],
         [-0.1952,  0.0483],
         [-0.2111,  0.1919],
         [-0.1258,  0.1610],
         [-0.0348,  0.2329],
         [ 0.3053,  0.2121]]], grad_fn=<ViewBackward0>), hidden_states=None, attentions=None)

In [ ]:
import torch

predictions = torch.argmax(
    outputs.logits,
    dim = 2
)

print(model.config.id2label)

{0: 'LABEL_0', 1: 'LABEL_1'}

In [ ]:
predicted_labels = []

# Flatten predictions to ensure it's a 1D tensor for iteration
predictions_flat = predictions.view(-1)

for prediction in predictions_flat:
  label_value = model.config.id2label[prediction.item()]
  predicted_labels.append(label_value)

print(predicted_labels)

['LABEL_0']

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification

# 1. Define a new sentence for NER
# This is the input text that we want to analyze for named entities.
text = "Barack Obama was born in Honolulu, Hawaii and later became the 44th President of the United States."

# 2. Load the tokenizer and model
# We load a pre-trained tokenizer and model specifically fine-tuned for Named Entity Recognition (NER).
# 'dslim/bert-base-NER' is a BERT-based model that has been trained on the CoNLL-2003 dataset
# for NER, which identifies persons (PER), organizations (ORG), locations (LOC), and miscellaneous (MISC).
tokenizer = AutoTokenizer.from_pretrained('dslim/bert-base-NER')
model = AutoModelForTokenClassification.from_pretrained('dslim/bert-base-NER')

# 3. Tokenize the new text
# The tokenizer converts the input text into a format that the model can understand.
# 'return_tensors='pt'' specifies that the output should be PyTorch tensors.
# The output 'inputs' will contain 'input_ids' (numerical representations of tokens)
# and 'attention_mask' (to differentiate real tokens from padding tokens).
inputs = tokenizer(text, return_tensors='pt')

# 4. Get model outputs
# We pass the tokenized inputs to the model to get its predictions.
# The 'outputs' object contains 'logits', which are the raw, unnormalized scores
# for each possible label for each token.
outputs = model(**inputs)

# 5. Extract predictions
# 'torch.argmax' is used to get the index of the highest logit score for each token along 'dim=2'.
# 'dim=2' refers to the dimension containing the scores for each label.
# This results in a tensor 'predictions' where each value is the predicted label ID for a token.
predictions = torch.argmax(
    outputs.logits,
    dim=2
)

# 6. Map predictions to labels
# We convert the numerical label IDs from 'predictions' back into human-readable label names
# using the model's configuration ('model.config.id2label').
# The 'predictions.view(-1)' flattens the tensor to make it easier to iterate through each token's prediction.
predicted_labels = []
predictions_flat = predictions.view(-1)

for prediction in predictions_flat:
  label_value = model.config.id2label[prediction.item()] # '.item()' extracts the scalar value from the tensor.
  predicted_labels.append(label_value)

# 7. Convert input IDs to human-readable tokens
# We convert the numerical input IDs back to their original word tokens using the tokenizer's 'convert_ids_to_tokens' method.
# '[0]' is used because 'input_ids' is typically batched, and we want the first (and only) sequence.
token_words = tokenizer.convert_ids_to_tokens(
    inputs['input_ids'][0]
)

# 8. Print token-label pairs
# This loop iterates through the original tokens and their corresponding predicted NER labels,
# displaying them in a clear, readable format.
# 'zip' is used to pair each token with its predicted label.
print(f"Text: {text}")
print("Named Entities:")
for word, predicted_label in zip(token_words, predicted_labels):
  print(f"{word} -> {predicted_label}")

# Expected Output Explanation:
# - [CLS] and [SEP]: Special tokens used by BERT, representing 'Classifier' (start of sentence) and 'Separator' (end of sentence). They are typically labeled 'O' (Outside).
# - B-PER: Beginning of a Person entity.
# - I-PER: Inside of a Person entity.
# - B-LOC: Beginning of a Location entity.
# - I-LOC: Inside of a Location entity.
# - O: Outside of any named entity.
# Notice how 'Barack' is 'B-PER' and 'Obama' is 'I-PER', indicating they form a single 'Person' entity.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Text: Barack Obama was born in Honolulu, Hawaii and later became the 44th President of the United States.
Named Entities:
[CLS] -> O
Barack -> B-PER
Obama -> I-PER
was -> O
born -> O
in -> O
Honolulu -> B-LOC
, -> O
Hawaii -> B-LOC
and -> O
later -> O
became -> O
the -> O
44 -> O
##th -> O
President -> O
of -> O
the -> O
United -> B-LOC
States -> I-LOC
. -> O
[SEP] -> O

In [ ]:
import torch

predictions = torch.argmax(
    ouputs.logits,
    dim = 2
)

print(predictions)