In [ ]:
import pandas as pd

data = {
    "Text": [
        "I LOVE this Phone!!! 😍",
        "Worst battery backup!!!",
        "Visit https://abc.com",
        "<h1>Excellent Camera</h1>",
        "Price is 50000 Rupees",
        "Amazing Performance!!!"
    ]
}

df = pd.DataFrame(data)
df.head()

                        Text
0     I LOVE this Phone!!! 😍
1    Worst battery backup!!!
2      Visit https://abc.com
3  <h1>Excellent Camera</h1>
4      Price is 50000 Rupees

In [ ]:
df['Text'] = df['Text'].str.lower()
df.head()

                        Text
0     i love this phone!!! 😍
1    worst battery backup!!!
2      visit https://abc.com
3  <h1>excellent camera</h1>
4      price is 50000 rupees

In [ ]:
df['Length'] = df['Text'].apply(len)  # this apply dunction is usefull
df.head()

                        Text  Length
0     i love this phone!!! 😍      22
1    worst battery backup!!!      23
2      visit https://abc.com      21
3  <h1>excellent camera</h1>      25
4      price is 50000 rupees      21

In [ ]:
for review in df['Text']:
  print(review)

i love this phone!!! 😍
worst battery backup!!!
visit https://abc.com
<h1>excellent camera</h1>
price is 50000 rupees
amazing performance!!!

In [ ]:
key = 'bad'
for  review in df['Text']:
  if key in review:
    print(review)

In [ ]:
# filter

df[df['sentiment']=='positive']

KeyError: 'sentiment'

In [ ]:
from collections import Counter

print(Counter(df['Text']))

Counter({'i love this phone!!! 😍': 1, 'worst battery backup!!!': 1, 'visit https://abc.com': 1, '<h1>excellent camera</h1>': 1, 'price is 50000 rupees': 1, 'amazing performance!!!': 1})

In [ ]:
for review in df['Text']:
  print(Counter(review))

Counter({' ': 4, '!': 3, 'i': 2, 'o': 2, 'e': 2, 'h': 2, 'l': 1, 'v': 1, 't': 1, 's': 1, 'p': 1, 'n': 1, '😍': 1})
Counter({'t': 3, '!': 3, 'r': 2, ' ': 2, 'b': 2, 'a': 2, 'w': 1, 'o': 1, 's': 1, 'e': 1, 'y': 1, 'c': 1, 'k': 1, 'u': 1, 'p': 1})
Counter({'t': 3, 'i': 2, 's': 2, '/': 2, 'c': 2, 'v': 1, ' ': 1, 'h': 1, 'p': 1, ':': 1, 'a': 1, 'b': 1, '.': 1, 'o': 1, 'm': 1})
Counter({'e': 4, '<': 2, 'h': 2, '1': 2, '>': 2, 'c': 2, 'l': 2, 'a': 2, 'x': 1, 'n': 1, 't': 1, ' ': 1, 'm': 1, 'r': 1, '/': 1})
Counter({'0': 4, 'e': 3, ' ': 3, 'p': 2, 'r': 2, 'i': 2, 's': 2, 'c': 1, '5': 1, 'u': 1})
Counter({'a': 3, '!': 3, 'm': 2, 'n': 2, 'e': 2, 'r': 2, 'z': 1, 'i': 1, 'g': 1, ' ': 1, 'p': 1, 'f': 1, 'o': 1, 'c': 1})

In [ ]:
import string

sentence = df['Text']

table = str.maketrans('','',string.punctuation)

clean_sentence = sentence.str.translate(table)
df['cleaned'] = clean_sentence
print(clean_sentence)

0      i love this phone 😍
1     worst battery backup
2        visit httpsabccom
3     h1excellent camerah1
4    price is 50000 rupees
5      amazing performance
Name: Text, dtype: object

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize , word_tokenize


for text_entry in df['Text']:
  print(sent_tokenize(text_entry))

for text_entry in df['Text']:
  for word in word_tokenize(text_entry):
    print(word)

['i love this phone!!!', '😍']
['worst battery backup!!', '!']
['visit https://abc.com']
['<h1>excellent camera</h1>']
['price is 50000 rupees']
['amazing performance!!', '!']
i
love
this
phone
!
!
!
😍
worst
battery
backup
!
!
!
visit
https
:
//abc.com
<
h1
>
excellent
camera
<
/h1
>
price
is
50000
rupees
amazing
performance
!
!
!

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
df

                        Text  Length                cleaned
0     i love this phone!!! 😍      22    i love this phone 😍
1    worst battery backup!!!      23   worst battery backup
2      visit https://abc.com      21      visit httpsabccom
3  <h1>excellent camera</h1>      25   h1excellent camerah1
4      price is 50000 rupees      21  price is 50000 rupees
5     amazing performance!!!      22    amazing performance

In [ ]:
# stop words

from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

stop_words = set(stopwords.words('english'))

stop_removed_sentences = []
for text in df['cleaned']:
  filtered_words = [word for word in word_tokenize(text) if word.lower() not in stop_words]
  stop_removed_sentences.append(' '.join(filtered_words))

df['stop_removed'] = stop_removed_sentences

df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Text,Length,cleaned,stopword_removed,stop_removed
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees

In [ ]:
# stemming
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

stemmer = PorterStemmer()

stemmed_sentences = []
for text in df['stop_removed']:
  stemmed_words = [stemmer.stem(word) for word in word_tokenize(text)]
  stemmed_sentences.append(' '.join(stemmed_words))

df['stemmed_text'] = stemmed_sentences

df.head()

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe

In [ ]:
# lemmatize - dictioary word

import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

lemmatizer = WordNetLemmatizer()

lemmatized_sentences = []
for text in df['stop_removed']:
  lemmatized_words = [lemmatizer.lemmatize(word) for word in word_tokenize(text)]
  lemmatized_sentences.append(' '.join(lemmatized_words))

df['lemmatized_text'] = lemmatized_sentences

df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee

In [ ]:
import re , string , nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer # Import necessary modules

# Download necessary NLTK data (quiet=True to suppress repeated messages if already downloaded)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True) # Ensure wordnet is downloaded for lemmatization

# Initialize NLP tools
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Start with the 'Text' column for processing
# We'll create a new column to store the fully processed text, to keep original 'Text' intact
df['fully_processed_text'] = df['Text'].copy()

# Lowercasing
df['fully_processed_text'] = df['fully_processed_text'].str.lower()

# URL removal
df['fully_processed_text'] = df['fully_processed_text'].str.replace(r'http?://\S+|www\.\S+','', regex=True)

# Punctuation removal
# Define a translation table once
translator = str.maketrans('', '', string.punctuation)
# Apply translation to each string in the Series
df['fully_processed_text'] = df['fully_processed_text'].apply(lambda x: x.translate(translator) if isinstance(x, str) else x)

# Tokenization, Stop word removal, Stemming, and Lemmatization in a single apply statement
# This processes each text entry through the remaining steps sequentially.
df['fully_processed_text'] = df['fully_processed_text'].apply(lambda text_input:
    ' '.join([lemmatizer.lemmatize(stemmer.stem(word))
              for word in word_tokenize(text_input)
              if word.lower() not in stop_words])
    if isinstance(text_input, str) else ""
)

# Display the DataFrame head with the new column
df.head()

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text,fully_processed_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup,worst batteri backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1,h1excel camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee,price 50000 rupe

In [ ]:
# post tagging

import nltk
nltk.download('averaged_perceptron_tagger_eng') # Changed to download the specific English tagger
nltk.download('wordnet') # Often needed for POS tagging or lemmatization context
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Apply pos_tag after tokenizing each string in the 'fully_processed_text' column
df['pos_tag'] = df['fully_processed_text'].apply(lambda x: pos_tag(word_tokenize(x)) if isinstance(x, str) else [])

df.head()

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text,fully_processed_text,pos_tag
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍,love phone 😍,"[(love, VB), (phone, NN), (😍, NN)]"
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup,worst batteri backup,"[(worst, JJS), (batteri, NN), (backup, NN)]"
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom,visit httpsabccom,"[(visit, NN), (httpsabccom, NN)]"
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1,h1excel camerah1,"[(h1excel, NN), (camerah1, NN)]"
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee,price 50000 rupe,"[(price, NN), (50000, CD), (rupe, NN)]"

In [ ]:
from nltk.chunk import RegexpParser
sentence="the intelligent student won the competition"
tokens=word_tokenize(sentence)
tags=pos_tag(tokens)
grammer="NP: {<DT>?<JJ>*<NN>}"
cp=RegexpParser(grammer)
result=cp.parse(tags)
print(result)

(S
  (NP the/DT intelligent/JJ student/NN)
  won/VBD
  (NP the/DT competition/NN))

In [ ]:
# Dependency Parsing

import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("John eats pizza.")

for token in doc:
    print(token.text, token.dep_, token.head.text)

displacy.render(doc, style="dep", jupyter=True)

John nsubj eats
eats ROOT eats
pizza dobj eats
. punct eats

In [ ]:
from spacy import displacy

nlp = spacy.load('en_core_web_sm')

doc = nlp('i love natural langugae process')

for entity in doc.ents:
    print(entity.text, entity.label_)

displacy.render(doc, style='ent', jupyter=True)

/usr/local/lib/python3.12/dist-packages/spacy/displacy/__init__.py:214: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  warnings.warn(Warnings.W006)

In [ ]:
from nltk.corpus import wordnet

car = wordnet.synsets('car')
print(car)


synonyms= []


for syn in wordnet.synsets('happy'):
  for lemma in syn.lemmas():
    synonyms.append(lemma.name())

print(set(synonyms))

[Synset('car.n.01'), Synset('car.n.02'), Synset('car.n.03'), Synset('car.n.04'), Synset('cable_car.n.01')]
{'well-chosen', 'glad', 'happy', 'felicitous'}

In [ ]:
import pandas as pd

import spacy
nlp = spacy.load('en_core_web_sm')

data = {'sentence':['elon musk founded spacex','apple realesed phone' ]}

df = pd.DataFrame(data)

for sentence in df['sentence']:
  doc = nlp(sentence)
  tokens = [t.text for t in doc]
  pos = [(t.text,t.pos) for t in doc]

  ents = [(e.text,e.label_) for e in doc.ents ]

print(tokens)
print(pos)
print(ents)

['apple', 'realesed', 'phone']
[('apple', <univ_pos_t.NOUN: 92>), ('realesed', <univ_pos_t.VERB: 100>), ('phone', <univ_pos_t.NOUN: 92>)]
[('apple', 'ORG')]