What is Natural Language Processing (NLP)? Explain in your own words how it acts
as a bridge between human language and computers

NLP gives the best pipelines to convert the human speakable labgauge into machine understandable format and helps the machine inturn to respond the sameway so humans talk to machines considering another human


T2
Why do computers need NLP to understand human language? Give one real-world
example to support your answer.

Computers need NLP because human language is complex and ambiguous, unlike the structured data they typically process. NLP allows them to interpret meaning.
Example: A chatbot needs NLP to understand customer queries like "I want to track my order" and respond appropriately.



List any four real-life applications of NLP and briefly describe what each one does.

1. Spam Detection: Identifies unwanted emails by analyzing text for suspicious patterns.
2. Sentiment Analysis: Determines the emotional tone (positive, negative, neutral) in text data.
3. Machine Translation: Translates text from one human language to another (e.g., Google Translate).
4. Chatbots/Virtual Assistants: Understands and responds to user commands or questions in natural language.

What is a rule-based NLP system? Explain using the spam detection example
(checking if "Congratulations" is present in a message).

A rule-based NLP system uses predefined linguistic rules or patterns to process text. It doesn't learn from data.
For spam detection, a rule could be: if the word "Congratulations" is in the message, label it as spam.

List and briefly explain the seven steps of the NLP pipeline, in the correct order.

1. Tokenization: Breaking text into smaller units (words/sentences).
2. Lowercasing: Converting all text to a uniform lowercase format.
3. Stopword Removal: Eliminating common, less meaningful words (e.g., "the", "is").
4. Stemming/Lemmatization: Reducing words to their root form.
5. Part-of-Speech Tagging: Labeling words with their grammatical role.
6. Named Entity Recognition: Identifying proper nouns (people, places, organizations).
7. Dependency Parsing: Analyzing grammatical relationships between words.

What is tokenization? Why is it a necessary step before a machine learning model
can process text?

Tokenization is the process of splitting text into smaller units called tokens (words, phrases, symbols).
It's necessary because ML models require numerical input, and tokenization breaks text into discrete items that can be converted into numerical representations.

What are stopwords? Give three examples of stopwords in English and explain why
they are usually removed

Stopwords are common words that appear frequently but often carry little semantic meaning. Examples: "the", "is", "and".
They are removed to reduce noise and dimensionality in text data, improving efficiency and focus on more important words.

Why is it important to convert all text data to lowercase before processing it in NLP?
Illustrate with an example.

Lowercasing standardizes text, treating words like "Apple", "apple", and "APPLE" as the same token. This prevents the model from treating them as distinct words.
Example: Without lowercasing, "Good" and "good" would be seen as different, leading to inconsistent analysis.


List any four common mistakes beginners make while working with pandas for NLP
tasks, as covered in the module.

1. Not converting text columns to string type (`.astype(str)`).
2. Misunderstanding `inplace=True` or not reassigning DataFrame modifications.
3. Incorrectly using string methods (`.str.method()`) vs. Python string methods.
4. Forgetting to handle missing values (NaN) before applying text operations.

Explain the difference between using = and == while filtering rows in a DataFrame,
and why mixing them up causes errors.

`=` is for assignment, used to give a value to a variable or column. `==` is for comparison, checking if two values are equal.
Mixing them up causes errors because `df[df['col'] = 'value']` attempts assignment within a boolean indexing context, which is invalid for comparison.

Write a Python program to store the sentence "I love Artificial Intelligence" in a
variable and print its data type using type().

In [1]:
v = 'i love artificial intelligence'
type(v)

str

Write a Python program to count the total number of characters in the sentence "I love
NLP" using len()

In [4]:
len(v)

30

Write a Python program that splits the sentence "I love Natural Language Processing"
into a list of words and prints how many words it contains

In [5]:
s = v.split(' ')
s

['i', 'love', 'artificial', 'intelligence']

4
Write a Python program using the in operator to check whether the word "free" is
present in the message "You have won a free prize".

In [6]:
m = 'you have won a free prize'
'free' in m

True

Write a Python program that checks if the word "Congratulations" is present in a
message, printing "Possible Spam" if it is and "Not Spam" otherwise.

In [7]:
m = ' congratulations you have won a free prize'
if 'congratulations' in m:
    print('possible spam')
else:
    print('not spam')

possible spam

Write Python code using pandas to create a DataFrame with two columns, "Review"
and "Sentiment", containing at least four sample rows

In [8]:
import pandas as pd

data = {
    'Review': [
        'This product is amazing!',
        'Absolutely terrible experience.',
        'It works as expected, no complaints.',
        'Could be better, but still usable.',
        'Best purchase ever, highly recommend!'
    ],
    'Sentiment': [
        'Positive',
        'Negative',
        'Neutral',
        'Negative',
        'Positive'
    ]
}

df = pd.DataFrame(data)
display(df.head())

                                  Review Sentiment
0               This product is amazing!  Positive
1        Absolutely terrible experience.  Negative
2   It works as expected, no complaints.   Neutral
3     Could be better, but still usable.  Negative
4  Best purchase ever, highly recommend!  Positive

Write Python statements to display the shape of a DataFrame using df.shape and its
summary using df.info().

In [9]:
df.shape

(5, 2)

.
P8
Write Python statements to display the first five and last five rows of a DataFrame
using df.head() and df.tail()

In [10]:
df.head()

                                  Review Sentiment
0               This product is amazing!  Positive
1        Absolutely terrible experience.  Negative
2   It works as expected, no complaints.   Neutral
3     Could be better, but still usable.  Negative
4  Best purchase ever, highly recommend!  Positive

In [11]:
df.tail()

                                  Review Sentiment
0               This product is amazing!  Positive
1        Absolutely terrible experience.  Negative
2   It works as expected, no complaints.   Neutral
3     Could be better, but still usable.  Negative
4  Best purchase ever, highly recommend!  Positive

Write a Python statement that uses value_counts() to count how many Positive and
Negative entries exist in a "Sentiment" column.

In [12]:
df['Sentiment'].value_counts()

Sentiment
Positive    2
Negative    2
Neutral     1
Name: count, dtype: int64

Write a Python statement using str.lower() to convert all entries in a "Review" column
of a DataFrame to lowercase.

In [13]:
df['Review'] = df['Review'].str.lower()
df['Review']

0                 this product is amazing!
1          absolutely terrible experience.
2     it works as expected, no complaints.
3       could be better, but still usable.
4    best purchase ever, highly recommend!
Name: Review, dtype: object

Write a Python statement using df["Review"].apply(len) to add a new "Length" column
showing the character count of each review

In [14]:
df['review_length'] = df['Review'].apply(len)
df['review_length']

0    24
1    31
2    36
3    34
4    37
Name: review_length, dtype: int64

In [15]:
df

                                  Review Sentiment  review_length
0               this product is amazing!  Positive             24
1        absolutely terrible experience.  Negative             31
2   it works as expected, no complaints.   Neutral             36
3     could be better, but still usable.  Negative             34
4  best purchase ever, highly recommend!  Positive             37

Write a Python program using a for loop to print every review in a DataFrame column
called "Review", one at a time.

In [16]:
for review in df['Review']:
    print(review)

this product is amazing!
absolutely terrible experience.
it works as expected, no complaints.
could be better, but still usable.
best purchase ever, highly recommend!

Write a Python statement using str.contains() to check whether the word "phone"
appears in each row of a "Review" column.

In [17]:
df['Review'].str.contains('phone')

0    False
1    False
2    False
3    False
4    False
Name: Review, dtype: bool

Write a Python statement to filter and display only the rows in a DataFrame where the
"Sentiment" column equals "Positive".

In [18]:
df[df['Sentiment']=='Positive']

                                  Review Sentiment  review_length
0               this product is amazing!  Positive             24
4  best purchase ever, highly recommend!  Positive             37

Write a Python statement using str.len() to add a "Characters" column showing the
character count of each review.

In [19]:
df['characters'] = df['Review'].str.len()
df['characters']

0    24
1    31
2    36
3    34
4    37
Name: characters, dtype: int64

Write a Python statement using apply(lambda x: len(x.split())) to add a "Words"
column showing the word count of each review.

In [20]:
df['word_count'] = df['Review'].apply(lambda x: len(x.split()))
df['word_count']

0    4
1    3
2    6
3    6
4    5
Name: word_count, dtype: int64

In [21]:
df

,Review,Sentiment,review_length,characters,word_count
0,this product is amazing!,Positive,24,24,4
1,absolutely terrible experience.,Negative,31,31,3
2,"it works as expected, no complaints.",Neutral,36,36,6
3,"could be better, but still usable.",Negative,34,34,6
4,"best purchase ever, highly recommend!",Positive,37,37,5

Create a dataset of six movie reviews with a Sentiment column, then write code to
display only the negative reviews.

Using the movie review dataset from the previous question, write code to find the
longest review based on its character length.

In [26]:
df[df['characters'] == df['characters'].max()]

,Review,Sentiment,review_length,characters,word_count
4,"best purchase ever, highly recommend!",Positive,37,37,5

Write code to count how many positive and how many negative reviews exist in your
six-review movie dataset using value_counts()

Create a dataset of 10 student feedback comments labeled Positive or Negative, then
write code to display the first five and last five records.