In [ ]:
import pandas as pd

data = {
    "Text": [
        "I LOVE this Phone!!! 😍",
        "Worst battery backup!!!",
        "Visit https://abc.com",
        "<h1>Excellent Camera</h1>",
        "Price is 50000 Rupees",
        "Amazing Performance!!!"
    ]
}

df = pd.DataFrame(data)
df.head()

                        Text
0     I LOVE this Phone!!! 😍
1    Worst battery backup!!!
2      Visit https://abc.com
3  <h1>Excellent Camera</h1>
4      Price is 50000 Rupees

In [ ]:
df['Text'] = df['Text'].str.lower()
df.head()

                        Text
0     i love this phone!!! 😍
1    worst battery backup!!!
2      visit https://abc.com
3  <h1>excellent camera</h1>
4      price is 50000 rupees

In [ ]:
df['Length'] = df['Text'].apply(len)  # this apply dunction is usefull
df.head()

                        Text  Length
0     i love this phone!!! 😍      22
1    worst battery backup!!!      23
2      visit https://abc.com      21
3  <h1>excellent camera</h1>      25
4      price is 50000 rupees      21

In [ ]:
for review in df['Text']:
  print(review)

i love this phone!!! 😍
worst battery backup!!!
visit https://abc.com
<h1>excellent camera</h1>
price is 50000 rupees
amazing performance!!!

In [ ]:
key = 'bad'
for  review in df['Text']:
  if key in review:
    print(review)

In [ ]:
# filter

df[df['sentiment']=='positive']

KeyError: 'sentiment'

In [ ]:
from collections import Counter

print(Counter(df['Text']))

Counter({'i love this phone!!! 😍': 1, 'worst battery backup!!!': 1, 'visit https://abc.com': 1, '<h1>excellent camera</h1>': 1, 'price is 50000 rupees': 1, 'amazing performance!!!': 1})

In [ ]:
for review in df['Text']:
  print(Counter(review))

Counter({' ': 4, '!': 3, 'i': 2, 'o': 2, 'e': 2, 'h': 2, 'l': 1, 'v': 1, 't': 1, 's': 1, 'p': 1, 'n': 1, '😍': 1})
Counter({'t': 3, '!': 3, 'r': 2, ' ': 2, 'b': 2, 'a': 2, 'w': 1, 'o': 1, 's': 1, 'e': 1, 'y': 1, 'c': 1, 'k': 1, 'u': 1, 'p': 1})
Counter({'t': 3, 'i': 2, 's': 2, '/': 2, 'c': 2, 'v': 1, ' ': 1, 'h': 1, 'p': 1, ':': 1, 'a': 1, 'b': 1, '.': 1, 'o': 1, 'm': 1})
Counter({'e': 4, '<': 2, 'h': 2, '1': 2, '>': 2, 'c': 2, 'l': 2, 'a': 2, 'x': 1, 'n': 1, 't': 1, ' ': 1, 'm': 1, 'r': 1, '/': 1})
Counter({'0': 4, 'e': 3, ' ': 3, 'p': 2, 'r': 2, 'i': 2, 's': 2, 'c': 1, '5': 1, 'u': 1})
Counter({'a': 3, '!': 3, 'm': 2, 'n': 2, 'e': 2, 'r': 2, 'z': 1, 'i': 1, 'g': 1, ' ': 1, 'p': 1, 'f': 1, 'o': 1, 'c': 1})

In [ ]:
import string

sentence = df['Text']

table = str.maketrans('','',string.punctuation)

clean_sentence = sentence.str.translate(table)
df['cleaned'] = clean_sentence
print(clean_sentence)

0      i love this phone 😍
1     worst battery backup
2        visit httpsabccom
3     h1excellent camerah1
4    price is 50000 rupees
5      amazing performance
Name: Text, dtype: object

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize , word_tokenize


for text_entry in df['Text']:
  print(sent_tokenize(text_entry))

for text_entry in df['Text']:
  for word in word_tokenize(text_entry):
    print(word)

['i love this phone!!!', '😍']
['worst battery backup!!', '!']
['visit https://abc.com']
['<h1>excellent camera</h1>']
['price is 50000 rupees']
['amazing performance!!', '!']
i
love
this
phone
!
!
!
😍
worst
battery
backup
!
!
!
visit
https
:
//abc.com
<
h1
>
excellent
camera
<
/h1
>
price
is
50000
rupees
amazing
performance
!
!
!

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
df

                        Text  Length                cleaned
0     i love this phone!!! 😍      22    i love this phone 😍
1    worst battery backup!!!      23   worst battery backup
2      visit https://abc.com      21      visit httpsabccom
3  <h1>excellent camera</h1>      25   h1excellent camerah1
4      price is 50000 rupees      21  price is 50000 rupees
5     amazing performance!!!      22    amazing performance

In [ ]:
# stop words

from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

stop_words = set(stopwords.words('english'))

stop_removed_sentences = []
for text in df['cleaned']:
  filtered_words = [word for word in word_tokenize(text) if word.lower() not in stop_words]
  stop_removed_sentences.append(' '.join(filtered_words))

df['stop_removed'] = stop_removed_sentences

df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Text,Length,cleaned,stopword_removed,stop_removed
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees

In [ ]:
# stemming
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

stemmer = PorterStemmer()

stemmed_sentences = []
for text in df['stop_removed']:
  stemmed_words = [stemmer.stem(word) for word in word_tokenize(text)]
  stemmed_sentences.append(' '.join(stemmed_words))

df['stemmed_text'] = stemmed_sentences

df.head()

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe

In [ ]:
# lemmatize - dictioary word

import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize # Ensure word_tokenize is imported if not already

lemmatizer = WordNetLemmatizer()

lemmatized_sentences = []
for text in df['stop_removed']:
  lemmatized_words = [lemmatizer.lemmatize(word) for word in word_tokenize(text)]
  lemmatized_sentences.append(' '.join(lemmatized_words))

df['lemmatized_text'] = lemmatized_sentences

df.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee

In [ ]:
import re , string , nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer # Import necessary modules

# Download necessary NLTK data (quiet=True to suppress repeated messages if already downloaded)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True) # Ensure wordnet is downloaded for lemmatization

# Initialize NLP tools
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Start with the 'Text' column for processing
# We'll create a new column to store the fully processed text, to keep original 'Text' intact
df['fully_processed_text'] = df['Text'].copy()

# Lowercasing
df['fully_processed_text'] = df['fully_processed_text'].str.lower()

# URL removal
df['fully_processed_text'] = df['fully_processed_text'].str.replace(r'http?://\S+|www\.\S+','', regex=True)

# Punctuation removal
# Define a translation table once
translator = str.maketrans('', '', string.punctuation)
# Apply translation to each string in the Series
df['fully_processed_text'] = df['fully_processed_text'].apply(lambda x: x.translate(translator) if isinstance(x, str) else x)

# Tokenization, Stop word removal, Stemming, and Lemmatization in a single apply statement
# This processes each text entry through the remaining steps sequentially.
df['fully_processed_text'] = df['fully_processed_text'].apply(lambda text_input:
    ' '.join([lemmatizer.lemmatize(stemmer.stem(word))
              for word in word_tokenize(text_input)
              if word.lower() not in stop_words])
    if isinstance(text_input, str) else ""
)

# Display the DataFrame head with the new column
df.head()

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text,fully_processed_text
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍,love phone 😍
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup,worst batteri backup
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom,visit httpsabccom
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1,h1excel camerah1
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee,price 50000 rupe

In [ ]:
# post tagging

import nltk
nltk.download('averaged_perceptron_tagger_eng') # Changed to download the specific English tagger
nltk.download('wordnet') # Often needed for POS tagging or lemmatization context
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# Apply pos_tag after tokenizing each string in the 'fully_processed_text' column
df['pos_tag'] = df['fully_processed_text'].apply(lambda x: pos_tag(word_tokenize(x)) if isinstance(x, str) else [])

df.head()

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Text,Length,cleaned,stopword_removed,stop_removed,stemmed_text,lemmatized_text,fully_processed_text,pos_tag
0,i love this phone!!! 😍,22,i love this phone 😍,!,love phone 😍,love phone 😍,love phone 😍,love phone 😍,"[(love, VB), (phone, NN), (😍, NN)]"
1,worst battery backup!!!,23,worst battery backup,!,worst battery backup,worst batteri backup,worst battery backup,worst batteri backup,"[(worst, JJS), (batteri, NN), (backup, NN)]"
2,visit https://abc.com,21,visit httpsabccom,!,visit httpsabccom,visit httpsabccom,visit httpsabccom,visit httpsabccom,"[(visit, NN), (httpsabccom, NN)]"
3,<h1>excellent camera</h1>,25,h1excellent camerah1,!,h1excellent camerah1,h1excel camerah1,h1excellent camerah1,h1excel camerah1,"[(h1excel, NN), (camerah1, NN)]"
4,price is 50000 rupees,21,price is 50000 rupees,!,price 50000 rupees,price 50000 rupe,price 50000 rupee,price 50000 rupe,"[(price, NN), (50000, CD), (rupe, NN)]"

In [ ]:
from nltk.chunk import RegexpParser
sentence="the intelligent student won the competition"
tokens=word_tokenize(sentence)
tags=pos_tag(tokens)
grammer="NP: {<DT>?<JJ>*<NN>}"
cp=RegexpParser(grammer)
result=cp.parse(tags)
print(result)

(S
  (NP the/DT intelligent/JJ student/NN)
  won/VBD
  (NP the/DT competition/NN))

In [ ]:
# Dependency Parsing

import spacy
from spacy import displacy

nlp = spacy.load("en_core_web_sm")
doc = nlp("John eats pizza.")

for token in doc:
    print(token.text, token.dep_, token.head.text)

displacy.render(doc, style="dep", jupyter=True)

John nsubj eats
eats ROOT eats
pizza dobj eats
. punct eats

In [ ]:
from spacy import displacy

nlp = spacy.load('en_core_web_sm')

doc = nlp('i love natural langugae process')

for entity in doc.ents:
    print(entity.text, entity.label_)

displacy.render(doc, style='ent', jupyter=True)

/usr/local/lib/python3.12/dist-packages/spacy/displacy/__init__.py:214: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  warnings.warn(Warnings.W006)

In [ ]:
from nltk.corpus import wordnet

car = wordnet.synsets('car')
print(car)


synonyms= []


for syn in wordnet.synsets('happy'):
  for lemma in syn.lemmas():
    synonyms.append(lemma.name())

print(set(synonyms))

[Synset('car.n.01'), Synset('car.n.02'), Synset('car.n.03'), Synset('car.n.04'), Synset('cable_car.n.01')]
{'well-chosen', 'glad', 'happy', 'felicitous'}

In [ ]:
import pandas as pd

import spacy
nlp = spacy.load('en_core_web_sm')

data = {'sentence':['elon musk founded spacex','apple realesed phone' ]}

df = pd.DataFrame(data)

for sentence in df['sentence']:
  doc = nlp(sentence)
  tokens = [t.text for t in doc]
  pos = [(t.text,t.pos) for t in doc]

  ents = [(e.text,e.label_) for e in doc.ents ]

print(tokens)
print(pos)
print(ents)

['apple', 'realesed', 'phone']
[('apple', <univ_pos_t.NOUN: 92>), ('realesed', <univ_pos_t.VERB: 100>), ('phone', <univ_pos_t.NOUN: 92>)]
[('apple', 'ORG')]

In [ ]:
# text - representaion - covnert text to numbers

sentences = [
    'i love NLP',
    'i love python',
    'nlp is  fun'
]

vocab = set()

for sentence in sentences:
  words = sentence.lower().split()
  for word in words:
    vocab.add(word)

print(vocab)   # position are changes , not in order

{'love', 'fun', 'nlp', 'is', 'i', 'python'}

In [ ]:
word_to_index = {}

for index , word in enumerate(vocab):
  word_to_index[word] = index

print(word_to_index)

{'love': 0, 'fun': 1, 'nlp': 2, 'is': 3, 'i': 4, 'python': 5}

In [ ]:
word = 'love'

vector = [0]*len(vocab)
vector[word_to_index[word]] = 1  # for that particular index make the 0 as 1
print(vector)

[1, 0, 0, 0, 0, 0]

In [ ]:
# bag of words - how many times the word has appeared

from collections import Counter

print(Counter(vocab))

Counter({'love': 1, 'fun': 1, 'nlp': 1, 'is': 1, 'i': 1, 'python': 1})

In [ ]:
# countvectorizer - text into bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    'i love python ',
    'i love NLP',
    'python is amazing'
]

for sentence in documents:
  words = sentence.lower().split()
  for word in words:
    vocab.add(word)

print(vocab)

vectorizer = CountVectorizer()
bag_of_words = vectorizer.fit_transform(documents)

print(bag_of_words.toarray())

{'love', 'fun', 'nlp', 'is', 'amazing', 'i', 'python'}
[[0 0 1 0 1]
 [0 0 1 1 0]
 [1 1 0 0 1]]

In [ ]:
You're right to notice that 'i' is a unique word in your documents list! The reason CountVectorizer produced a 3x5 matrix instead of 3x6 is due to its default tokenization pattern.
By default, CountVectorizer's token_pattern is set to r'(?u)\b\w\w+\b',
which means it only considers words with two or more alphanumeric
characters.
This pattern ignores single-character words like 'i'.

I'll add a cell to show the vocabulary the CountVectorizer
actually used, and then another cell demonstrating how to include
 single-character words by modifying the token_pattern.

In [ ]:
# n grams , unigram , Bigram , Trigram


documents = [
    'i love python ',
    'i love NLP',
    'python is amazing'
]
CountVectorizer(ngram_range=(1,1)) # for bi grams (2,2) ,
vectorizer = CountVectorizer(ngram_range=(1,1))
bag_of_words = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(bag_of_words.toarray())

['amazing' 'is' 'love' 'nlp' 'python']
[[0 0 1 0 1]
 [0 0 1 1 0]
 [1 1 0 0 1]]

In [ ]:
from nltk.stem.snowball import DutchStemmer
bag of words give equal importance to all of them

tf - term frequency ()   - occurences of word in doc / total num of words in docu
* if tf is more , the word is more impt within that document

idf - inverse document frequency
- how rare a word is across all DutchStemmer
idf = log(total num of cos/ documnet containing that word )



tf-idf = tf x IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
documents = [
    'i love python ',
    'i love NLP',
    'python is amazing'
]

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(x.toarray())

['amazing' 'is' 'love' 'nlp' 'python']
[[0.         0.         0.70710678 0.         0.70710678]
 [0.         0.         0.60534851 0.79596054 0.        ]
 [0.62276601 0.62276601 0.         0.         0.4736296 ]]

In [ ]:
hashing vectorizer - text to numbers without creating pr storing vocabulary
no vocab means

In [ ]:
!pip install gensim
from gensim.models import Word2Vec

sentences = [
   ['i', 'love', 'python'],
   ['python','is','easy'],
   ['machine','learning','is','powerful']

]

cbow_model = Word2Vec(
    sentences,
    vector_size = 100,
    window = 2,
    sg = 0,           # cbow  for 1 - skipgram
    min_count = 1,
    epochs = 100
)

print(cbow_model.wv['python'])

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.2)
[-8.6186556e-03  3.6664475e-03  5.1880055e-03  5.7427413e-03
  7.4666589e-03 -6.1659538e-03  1.1055603e-03  6.0494691e-03
 -2.8437153e-03 -6.1714565e-03 -4.1010563e-04 -8.3694672e-03
 -5.5969027e-03  7.1054213e-03  3.3538081e-03  7.2222599e-03
  6.8019289e-03  7.5335195e-03 -3.7936156e-03 -5.6556391e-04
  2.3471694e-03 -4.5190072e-03  8.3877370e-03 -9.8599447e-03
  6.7681479e-03  2.9115318e-03 -4.9294168e-03  4.4007129e-03
 -1.7432281e-03  6.7110676e-03  9.9638598e-03 -4.3648244e-03
 -5.9981423e-04 -5.6972927e-03  3.8466386e-03  2.7853842e-03
  6.8919491e-03  6.1001745e-03  9.5379045e-03  9.2708860e-03
  7.8929076e-03 -6.9868155e-03 -9.1568716e-03 -3.5439187e-04
 -3.0981712e-03  7.8950338e-03  5.9366459e-03 -1.5443000e-03
  1.5102139e-03  1.7915977e-03  7.8153042e-03 -9.5090345e-03
 -2.0913887e-04  3.4662553e-03 -9.4019901e-04  8.3776983e-03
  9.0102004e-03  6.5327678e-03 -7.1462448e-04  7.7102813e-03
 -8.5322112e-03  3.2055466e-03 -4.6353671e-03 -5.0895372e-03
  3.5862906e-03  5.3736004e-03  7.7710035e-03 -5.7627778e-03
  7.4294615e-03  6.6271732e-03 -3.7066345e-03 -8.7409485e-03
  5.4380312e-03  6.5075764e-03 -7.8764604e-04 -6.7060255e-03
 -7.0799687e-03 -2.4956805e-03  5.1409067e-03 -3.6665609e-03
 -9.3685295e-03  3.8239798e-03  4.8821308e-03 -6.4262711e-03
  1.2076806e-03 -2.0761450e-03  2.3919200e-05 -9.8860702e-03
  2.6940678e-03 -4.7479011e-03  1.0862070e-03 -1.5738640e-03
  2.2004251e-03 -7.8820037e-03 -2.7118949e-03  2.6660392e-03
  5.3460784e-03 -2.3926506e-03 -9.5058205e-03  4.5042080e-03]

In [ ]:
from nltk import corpus
GLoVe - Global vectors

instaed of predicting form the local context it learns form global
word co-occurences statistics across the entore corpus

In [ ]:
from nltk.translate import api
import gensim.downloader as api

glove = api.load('glove-wiki-gigaword-50')

print(glove['computer'][:10])

[==================================================] 100.0% 66.0/66.0MB downloaded
[ 0.079084 -0.81504   1.7901    0.91653   0.10797  -0.55628  -0.84427
 -1.4951    0.13418   0.63627 ]

In [ ]:
# FAsT TEXT - instaed of learning whole words only . learns parts of words

gets the root word only and vectorizes it - ( player , playing , played)
all consider to play

## Word Embedding Creation Techniques

Word embeddings are dense vector representations of words that capture semantic relationships between them. Words with similar meanings or that appear in similar contexts will have similar vector representations. Here's a breakdown of some popular techniques:

### 1. Word2Vec

*   **Core Idea**: Word2Vec is a predictive model that learns word embeddings by trying to predict the context of words or predict words from their context. It's a shallow neural network model.
*   **Two Architectures**:
    *   **Continuous Bag-of-Words (CBOW)**: Predicts a target word from its surrounding context words. It's faster and better for frequent words.
    *   **Skip-gram**: Predicts surrounding context words given a target word. It's slower but performs better for infrequent words.
*   **Local Context**: Word2Vec focuses on learning embeddings based on the *local context* of words (words that appear close to each other in sentences).
*   **Training**: It uses a sliding window to define context and optimizes the word vectors to maximize the probability of context words given a target word (Skip-gram) or vice-versa (CBOW).

### 2. GloVe (Global Vectors for Word Representation)

*   **Core Idea**: GloVe is a count-based model that combines the advantages of both global matrix factorization (like LSA) and local context window methods (like Word2Vec).
*   **Global Co-occurrence Statistics**: Instead of solely relying on local context, GloVe learns word embeddings by analyzing the *global word-word co-occurrence statistics* from the entire corpus.
*   **Co-occurrence Matrix**: It constructs a large co-occurrence matrix, where each cell (i, j) represents how many times word `i` and word `j` appear together in the corpus within a specified window.
*   **Objective**: GloVe's objective function aims to learn word vectors such that their dot product is proportional to the logarithm of their co-occurrence probability. This directly models the ratios of word co-occurrence probabilities.

### 3. FastText

*   **Core Idea**: FastText extends Word2Vec by representing each word as a bag of character n-grams (subwords). This allows it to learn embeddings for out-of-vocabulary (OOV) words and handle morphology effectively.
*   **Subword Information**: For example, the word "eating" might be represented as `<ea`, `eat`, `ati`, `tin`, `ing>`. The vector for "eating" is the sum of its character n-gram vectors.
*   **Benefits**:
    *   **OOV Handling**: Can infer vectors for words not seen during training by summing up the vectors of their character n-grams.
    *   **Morphology**: Captures morphological similarities (e.g., "play," "playing," "played" will have similar components due to shared subwords).
    *   **Reduced Vocabulary Size**: By using subwords, it can represent a vast vocabulary with a smaller set of subword units.
*   **Training**: Similar to Skip-gram or CBOW, but instead of words, it predicts context based on subword representations.

### 4. Byte Pair Encoding (BPE)

*   **Core Idea**: Byte Pair Encoding (BPE) is a data compression algorithm that is surprisingly effective for tokenization in Natural Language Processing (NLP), especially for large language models. It works by iteratively merging the most frequent adjacent character or character-sequence pairs into new, single tokens.

*   **Process**:
    1.  **Initialize Vocabulary**: Start with a vocabulary of all unique characters in the text.
    2.  **Count Pairs**: Count the frequency of all adjacent pairs of characters/tokens.
    3.  **Merge Most Frequent**: Replace all occurrences of the most frequent pair with a new, merged token.
    4.  **Repeat**: Repeat steps 2 and 3 for a predefined number of merges (or until no more merges are possible), gradually building up a vocabulary of common words and subword units.

*   **Why it's seen in Tokenization (especially for LLMs)**:
    *   **Handles Unknown Words (OOV)**: Unlike pure word-based tokenization, BPE can break down rare or unseen words into known subword units, allowing models to process them instead of treating them as 'unknown' tokens. For example, 'unhappiness' might become 'un', 'happy', 'ness'.
    *   **Manages Vocabulary Size**: It strikes a balance between character-level (very large sequences, but small vocabulary) and word-level (smaller sequences, but potentially huge vocabulary with many rare words) tokenization. BPE creates a manageable vocabulary that includes common words and effective subword units for less common words.
    *   **Captures Morphology**: By breaking words into subwords, BPE naturally captures morphological information (prefixes, suffixes, roots), which helps the model understand word variations.
    *   **Efficient Representation**: It often results in shorter token sequences than character-level tokenization and can represent a vast range of words more efficiently than pure word-level tokenization, which is crucial for the computational efficiency of large models.
    *   **Common in LLMs**: BPE and its variants (like WordPiece and SentencePiece) are widely used in transformer-based models (e.g., GPT, BERT) because they effectively handle diverse text, reduce the impact of out-of-vocabulary words, and create robust representations.

### Examples of BPE, WordPiece, and SentencePiece Tokenization

Let's use your example words: "able", "stable", and "understandable". These words are great for illustrating how these methods identify and reuse common subword units.

#### 1. Byte Pair Encoding (BPE) Example

BPE starts with individual characters and iteratively merges the most frequent adjacent pairs. If 'able' is a very common suffix or standalone word, BPE will learn it as a fundamental token.

Let's assume we have a corpus where `able` is a frequent word and suffix. The BPE algorithm would proceed as follows:

*   **Initial Vocabulary**: `a, b, l, e, s, t, n, d, r, u, <space>` (and all other characters in the corpus)

*   **Example Merges (simplified for illustration, actual merges depend on corpus frequency)**:
    1.  Frequent pair `ab` merges to `ab`.
    2.  Frequent pair `le` merges to `le`.
    3.  The pair `ab` followed by `le` is very frequent (e.g., in `able`, `table`). So, `able` might merge to `able`.
    4.  Similarly, `st` is a frequent pair, merging to `st`.
    5.  `under` and `stand` might become tokens.

*   **Tokenization for your words, assuming `able`, `st`, `understand` are learned tokens**:
    *   `"able"`              -> `['able']`
    *   `"stable"`            -> `['st', 'able']`
    *   `"understandable"`  -> `['understand', 'able']`

    *Key Takeaway*: Once `able` becomes a learned token, BPE efficiently reuses it. This significantly reduces the vocabulary size while allowing the model to compose novel words from known subword units (e.g., `un` + `st` + `able` if `un` was also a token).

#### 2. WordPiece Example

WordPiece (used in BERT) also learns subword units, often using a `##` prefix to indicate that a token is a continuation of a word. It focuses on statistically significant subword units, minimizing the number of pieces a word is broken into.

For `"able"`, `"stable"`, `"understandable"`:

*   `"able"`              -> `['able']` (as a common base word)
*   `"stable"`            -> `['st', '##able']` (or `['s', '##table']` if 'st' isn't as strong, but 'able' is the key recurring unit). The `##` indicates 'able' is not a standalone word here.
*   `"understandable"`  -> `['understand', '##able']` (assuming `understand` is a learned token and `##able` is the recurring suffix).

    *Key Takeaway*: The `##` prefix is crucial. It differentiates `able` (a standalone word) from `##able` (a suffix). This allows WordPiece to manage a vocabulary that effectively represents both full words and common affixes/subword components, handling morphology and out-of-vocabulary words without creating entirely new tokens.

#### 3. SentencePiece Example

SentencePiece (used in models like T5, XLNet) is distinctive because it treats the entire input as a sequence of characters, *including spaces*, then applies BPE or the Unigram algorithm. Spaces are explicitly part of the tokens, usually as a leading ` `.

For `"able"`, `"stable"`, `"understandable"` (assuming space is represented by ` `):

*   `" able"`              -> `[' able']` (the leading space indicates it's a standalone word)
*   `" stable"`            -> `[' stable']` (SentencePiece often keeps frequent words like 'stable' as a single token, aiming for a short tokenization while preserving reconstruction ability.)
*   `" understandable"`  -> `[' understand', 'able']` (Here, ` understandable` is broken down. ` understand` is a common word with a leading space. `able` is then a suffix without a leading space because it's part of a larger word.)
    *   Alternatively, depending on the model and corpus, it could also be tokenized as: `[' under', 'stand', 'able']` if `under` and `stand` are very strong subword units.

    *Key Takeaway*: SentencePiece's explicit handling of spaces means that ` able` as a standalone word is distinct from `able` when it appears as a subword within another word (e.g., in ` understandable`). This ensures precise reconstruction of the original text, including whitespace, which is beneficial for tasks like machine translation or text generation where exact output formatting matters. It's highly flexible and can adapt to different languages and text patterns without pre-tokenization.

## Understanding Word Vector Embeddings: CBOW, GloVe, and FastText

Word embeddings are dense vector representations of words that capture semantic relationships. They allow us to perform mathematical operations on words, reflecting their meanings and contexts.

### 1. Vector Embeddings: The Core Idea

**What they are**: Word embeddings are numerical representations (vectors) of words. Each word is mapped to a vector of real numbers (e.g., a 100-dimensional vector).

**Why they are useful**: Words with similar meanings or that appear in similar contexts will have similar vector representations. This allows machine learning models to understand the nuances of language better than one-hot encoding or bag-of-words approaches.

**Example**: In a well-trained embedding space:
*   `vector('king') - vector('man') + vector('woman')` might be close to `vector('queen')`
*   `vector('walking') - vector('walk')` might be similar to `vector('swimming') - vector('swim')` (capturing the 'ing' suffix meaning)

Let's dive into some prominent methods for creating these embeddings.

### 2. CBOW (Continuous Bag-of-Words) - A Word2Vec Model

CBOW is one of the two main architectures in Word2Vec. It's designed to predict a target word given its surrounding context words.

**Core Idea**: Given a window of context words, predict the middle word.

**Detailed Step-by-Step Flow (Simplified)**:

1.  **Input**: Consider a sentence: "The quick brown `fox` jumps over the lazy dog."
    *   If `fox` is the target word, a context window of size 2 (2 words before, 2 words after) would be: `[quick, brown, ___, jumps, over]`.

2.  **One-Hot Encoding**: Each context word (`quick`, `brown`, `jumps`, `over`) is converted into a one-hot vector.

3.  **Embedding Layer (Projection)**: These one-hot vectors are then fed into a neural network (specifically, an embedding layer). This layer has a weight matrix `W` (the input-to-hidden weight matrix). Multiplying the one-hot vector by `W` effectively "looks up" the embedding vector for that word.
    *   `embedding_vector(quick) = W[index_of_quick]`
    *   `embedding_vector(brown) = W[index_of_brown]`
    *   ... and so on.

4.  **Averaging Context Embeddings**: The embedding vectors for all context words are averaged to create a single "context vector".
    *   `context_vector = (embedding(quick) + embedding(brown) + embedding(jumps) + embedding(over)) / 4`

5.  **Output Layer**: This `context_vector` is then fed through another linear layer (with a weight matrix `W'`) and a softmax activation function. The goal is to produce a probability distribution over the entire vocabulary.

6.  **Prediction**: The word with the highest probability from the output distribution is the model's prediction for the target word.

7.  **Learning**: The model compares its predicted word with the actual target word (`fox`). The error is used to update the weight matrices `W` and `W'` (and thus the word embeddings) through backpropagation, nudging them to make better predictions in the future. After training, the `W` matrix contains the learned word embeddings.

**Example**: If the context is `[quick, brown, ___, jumps, over]`, CBOW tries to predict `fox`.

### 3. GloVe (Global Vectors for Word Representation)

GloVe takes a different approach, combining global statistical information (like co-occurrence counts) with local context window methods.

**Core Idea**: GloVe learns word embeddings by analyzing the global word-word co-occurrence statistics across the entire corpus. The key insight is that ratios of word-word co-occurrence probabilities have meaning.

**Detailed Step-by-Step Flow**:

1.  **Build Co-occurrence Matrix (X)**: Scan the entire corpus and construct a co-occurrence matrix `X`. `X_ij` represents how many times word `j` appears in the context of word `i` within a predefined window size.
    *   **Example Corpus**: "I like apples. I like oranges. I like fruit."
    *   Window size = 1 (words immediately next to each other)
    *   If `i` is 'like' and `j` is 'apples', `X_i,j` would be 1.
    *   If `i` is 'I' and `j` is 'like', `X_i,j` would be 3.

2.  **Define Objective Function**: GloVe's objective function minimizes the difference between the dot product of two word vectors (`w_i` and `w_j`) and the logarithm of their co-occurrence count (`log(X_ij)`).
    *   The function also includes bias terms (`b_i`, `b_j`) and a weighting function `f(X_ij)` that gives less weight to very rare or very common co-occurrences.
    *   `Loss = sum(f(X_ij) * (w_i^T * w_j + b_i + b_j - log(X_ij))^2)`

3.  **Train the Model**: This objective function is optimized (e.g., using gradient descent) to learn the word vectors (`w_i`) and context word vectors (`w_j`), as well as the bias terms.

4.  **Final Embeddings**: After training, the learned `w_i` vectors (and sometimes `w_j` vectors) are used as the word embeddings.

**Example**: Consider the words "ice" and "steam".
*   `P(solid | ice)` will be high, `P(gas | steam)` will be high.
*   `P(fashion | ice)` will be low, `P(fashion | steam)` will be low.
*   GloVe captures these ratios of co-occurrence probabilities. For instance, the ratio `P(k | ice) / P(k | steam)` should be large for words `k` like "solid" or "cold", and small for words `k` like "gas" or "hot". It should be close to 1 for generic words `k` like "the" or "a". GloVe learns vectors that encode these relationships.

### 4. FastText

FastText, developed by Facebook, is an extension of Word2Vec that addresses its limitations, particularly with out-of-vocabulary (OOV) words and morphological rich languages.

**Core Idea**: Instead of learning vectors for entire words, FastText learns vectors for character n-grams (subwords) and then sums these up to get a word's vector. It can still learn entire word vectors, but the subword aspect is its key differentiator.

**Detailed Step-by-Step Flow**:

1.  **Subword Generation**: For each word in the corpus, FastText generates all its character n-grams. It also adds special boundary markers `<` and `>` to differentiate between prefixes/suffixes and the full word.
    *   **Example**: For the word "`apple`" and n-gram range (3, 6):
        *   Character n-grams: `<ap`, `app`, `ppl`, `ple`, `le>`, `<app`, `appl`, `pple`
        *   Full word itself is also included: `apple`

2.  **Embedding Subwords**: Each character n-gram (subword) is assigned its own embedding vector. This is analogous to how words get embedding vectors in Word2Vec.

3.  **Word Embedding as Sum of Subword Embeddings**: The vector for a full word is obtained by summing the vectors of all its constituent character n-grams.
    *   `vector('apple') = vector('<ap') + vector('app') + ... + vector('ple>') + vector('apple')`

4.  **Training**: The training process is similar to Word2Vec's Skip-gram or CBOW, but instead of predicting words or contexts based on single word vectors, it uses these summed subword vectors.

**Benefits & Examples**:
*   **OOV Handling**: If the word "`unbelievable`" is not seen during training, FastText can still form its vector by summing the vectors of its known subwords like `un`, `believe`, `able`.
*   **Morphology**: Words like "`run`", "`running`", and "`runner`" will have similar vectors because they share common subwords (e.g., `run`). This helps in languages with rich morphology.
*   **Reduced Vocabulary for Rare Words**: Very rare words can still get meaningful representations because their subwords are likely to be present in other words in the corpus.

**Example**: If the model has learned vectors for `play`, `ing`, `ed`:
*   `vector('playing')` can be approximated by `vector('play') + vector('ing')`
*   `vector('played')` can be approximated by `vector('play') + vector('ed')`

This makes FastText particularly robust for handling typos, rare words, and morphologically complex languages.

### 5. Hashing Vectorizer

The Hashing Vectorizer is another technique to convert text documents into numerical feature vectors, similar to `CountVectorizer` or `TfidfVectorizer`, but with a key difference: it doesn't store an explicit vocabulary.

**Core Idea**: Instead of mapping words to unique indices in a vocabulary list, it uses a hashing function to map words directly to feature indices. This means it can convert text to numbers without ever seeing all the words in advance.

**Detailed Step-by-Step Flow (Simplified)**:

1.  **Input**: You provide a list of text documents (e.g., sentences, reviews).

2.  **Tokenization**: Each document is first tokenized into individual words (or n-grams, depending on configuration), just like with other vectorizers.
    *   **Example Document**: "i love python"
    *   Tokens: `['i', 'love', 'python']`

3.  **Hashing Function**: For each token, a hashing function (like the built-in `hash()` function in Python, or a more sophisticated one like `MurmurHash`) is applied. This function converts the token (a string) into an integer number.
    *   `hash('i')` -> some_integer_1
    *   `hash('love')` -> some_integer_2
    *   `hash('python')` -> some_integer_3

4.  **Modulo Operation**: The integer output from the hash function is then put through a modulo operation (`%`) with a predefined number of features (e.g., `n_features = 2^18`). This ensures that the resulting index falls within a fixed range, effectively mapping each token to one of the `n_features` bins.
    *   `some_integer_1 % n_features` -> final_index_1
    *   `some_integer_2 % n_features` -> final_index_2
    *   `some_integer_3 % n_features` -> final_index_3

5.  **Vector Construction**: A sparse vector of size `n_features` is created for each document. For every token in the document, the corresponding feature index (obtained from the hashing and modulo) has its count incremented by 1.
    *   For "i love python", if `final_index_1`, `final_index_2`, `final_index_3` are distinct, the vector will have 1s at those positions and 0s elsewhere.

    *   **Sign Flipping (Optional but Common)**: To mitigate collisions and ensure features are less correlated, some implementations (like scikit-learn's `HashingVectorizer`) also multiply the hash value by -1 if the original hash value is negative. This helps distribute hashes more evenly.

**Advantages (Why use it)**:

*   **Scalability**: Excellent for very large datasets or online learning. It doesn't need to store a potentially massive vocabulary in memory.
*   **Memory Efficiency**: Uses less memory than `CountVectorizer` or `TfidfVectorizer` because there's no explicit vocabulary dictionary to maintain.
*   **No OOV (Out-of-Vocabulary) Issues**: Every word, even if unseen during training, will get mapped to an index, so there are no "unknown word" errors. This is similar to FastText's subword approach but simpler.
*   **Stateless**: Can be used in streaming scenarios where new data is continuously arriving, as it doesn't need to fit on a corpus first to build a vocabulary.

**Disadvantages (When to be cautious)**:

*   **Hash Collisions**: Different words can (rarely) map to the same feature index, leading to "collisions." This can sometimes reduce the model's accuracy, although with a large enough `n_features`, the impact is usually minimal.
*   **Lack of Interpretability**: Because there's no stored vocabulary, you can't easily map a feature index back to a specific word. If you want to know which words are most important to your model, this is not the right choice.
*   **Fixed Feature Size**: The number of features (`n_features`) must be set in advance. If it's too small, collisions are more likely. If it's too large, it might be inefficient.

**In Simple Terms**: Think of it like assigning each word to a numbered locker in a very large gym, but instead of having a list of which word goes to which locker, you just have a rule (the hashing function) that tells you which locker to put a word in. You don't care if two different words accidentally end up in the same locker, as long as there are enough lockers that it doesn't happen too often to mess things up.

### Comparison Table: CBOW, GloVe, and FastText

Here's a table summarizing the key differences between these popular word embedding techniques:

| Feature             | CBOW (Word2Vec)                                | GloVe (Global Vectors)                                  | FastText                                             |
| :------------------ | :--------------------------------------------- | :------------------------------------------------------ | :--------------------------------------------------- |
| **Core Approach**   | Predicts center word from context words.       | Learns from global word-word co-occurrence statistics. | Extends Word2Vec by learning from character n-grams (subwords). |
| **Context**         | Local context (sliding window).                | Global context (co-occurrence matrix across corpus).    | Local context (sliding window, but with subwords).   |
| **Input Unit**      | Whole words.                                   | Whole words.                                            | Character n-grams (subwords) and whole words.        |
| **OOV Handling**    | Poor. Cannot generate embeddings for unseen words; typically assigned a random or zero vector. | Poor. Cannot generate embeddings for unseen words; typically assigned a random or zero vector. | Good. Can construct embeddings for OOV words by summing their known subword vectors. |
| **Morphology**      | Limited. Treats morphological variations as distinct words. | Limited. Treats morphological variations as distinct words. | Good. Captures morphological information (prefixes, suffixes, roots) due to subword learning. |
| **Training Data**   | Requires large amounts of text data.           | Requires large amounts of text data (corpus for co-occurrence counts). | Requires large amounts of text data.                 |
| **Interpretability**| Hidden layer weights represent word embeddings. | Directly minimizes a function related to co-occurrence ratios. | Hidden layer weights for subwords and words.         |
| **Speed (Training)**| Generally faster than Skip-gram for frequent words. | Can be slower than Word2Vec for very large datasets due to matrix construction. | Similar to Word2Vec, but subword processing adds some overhead. |
| **Strengths**       | Efficient for common words, good at capturing semantic relationships. | Effectively captures semantic relationships and analogies, leverages global statistics. | Robust for OOV words, handles morphological-rich languages well, good for smaller corpora. |
| **Weaknesses**      | Struggles with rare words and OOV.             | Struggles with rare words and OOV. Interpreting the objective function can be complex. | Larger model size due to storing subword embeddings. Can be slower to train than CBOW for certain tasks. |
| **Used in Models**  | Word2Vec (various NLP tasks).                  | Many NLP models, often as pre-trained embeddings.       | Often used for text classification, sentiment analysis, and in some transfer learning scenarios. |

This table should provide a clear overview of when to choose each method based on your specific NLP task and data characteristics.